/* test-s07b: Modelos de consultoria B (item 5). rt-models3.js/.css: sete modelos novos — mapa de stakeholders (poder × interesse),
   Business Model Canvas e Balanced Scorecard (Estratégia), cadeia de valor e curva da mudança / ADKAR (Processos), jornada do cliente
   (Evolução), OKR (Indicadores) — cada um com 3–4 efeitos, edição no slide ([data-e]), campos no painel, gancho norm, palavras-chave;
   oito presets (Ansoff, Eisenhower, Kano, SCR, Minto, Iceberg, 5W2H, SIPOC) sobre motores existentes (AMRT.PRESETS + gancho label);
   Biblioteca de modelos com chips de categoria, busca e prévias só nos cards visíveis (rolagem religa); inserir/arrastar presets;
   stageCheck em branco/navy e 100 %/50 %, paleta A&M (nunca vermelho), dados hostis, vitrine, apresentação + Ampliar (rodapé com o
   nome do preset), saneamento ao abrir, export autônomo (CR-04) e reabertura.
   Uso: python3 assemble.py && node test-s07b.js (o qa-gate.sh pega qualquer test-s[0-9][0-9]*.js) */
process.env.NODE_PATH='/opt/node22/lib/node_modules'; require('module').Module._initPaths();
const {chromium}=require('playwright'); const path=require('path'); const fs=require('fs'); const os=require('os');
const FILE='file://'+path.join(__dirname,'AM-Studio-Editor.html');
const FONTS=process.env.AM_FONTS_DIR||path.join(__dirname,'..','fonts2');
const SHOTS=path.join(__dirname,'shots'); fs.mkdirSync(SHOTS,{recursive:true});
const SH=f=>path.join(SHOTS,'s07b-'+f+'.png');
const TMP=fs.mkdtempSync(path.join(os.tmpdir(),'canteiro-s07b-'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const results=[]; let failed=0; const errs=[];
function check(name, ok, info){ results.push((ok?'PASS ':'FAIL ')+name+(info!==undefined&&!ok?'  '+JSON.stringify(info):'')); if(!ok) failed++; }
async function fonts(p){ if(!fs.existsSync(path.join(FONTS,'gf.css'))) return;
  await p.route('https://fonts.googleapis.com/**',r=>r.fulfill({status:200,contentType:'text/css',body:fs.readFileSync(path.join(FONTS,'gf.css'),'utf8')}));
  await p.route('https://fonts.gstatic.com/**',r=>{const f=path.join(FONTS,path.basename(new URL(r.request().url()).pathname)); return fs.existsSync(f)?r.fulfill({status:200,contentType:'font/woff2',body:fs.readFileSync(f)}):r.abort();}); }
async function page(ctx, url, tag, wait){ const p=await ctx.newPage(); await fonts(p);
  p.on('pageerror',e=>errs.push(tag+' pageerror: '+e.message));
  p.on('console',m=>{ if(m.type()==='error'&&!/net::|Failed to load/.test(m.text())) errs.push(tag+': '+m.text()); });
  if(url) await p.goto(url); await sleep(wait||800); return p; }
const fresh=p=>p.evaluate(()=>{ AMStudio.closeMenus(); AMStudio.loadDeck(AMStudio.newDeck(),null,true,true); });
const deckJSON=html=>{ const m=html.match(/<script type="application\/json" id="am-deck-data">([\s\S]*?)<\/script>/); return m?JSON.parse(m[1]):null; };
const KINDS=['stake','valuechain','bmc','journey','okr','bsc','change'];
const CAT={stake:'Estratégia',valuechain:'Processos',bmc:'Estratégia',journey:'Evolução',okr:'Indicadores',bsc:'Estratégia',change:'Processos'};
const ROOT={stake:'.fxsk',valuechain:'.fxvc',bmc:'.fxbm',journey:'.fxjr',okr:'.fxok',bsc:'.fxbs',change:'.fxch'};
const PRESETS={ansoff:'matrix',eisenhower:'matrix',kano:'matrix',scr:'cardgrid',minto:'smart',iceberg:'smart',w5h2:'cardgrid',sipoc:'smart'};
/* paleta A&M + cinzas/gelos já usados pelo runtime + branco/transparente: toda cor dos modelos tem de estar aqui (nunca vermelho) */
const PAL=['#002A46','#4A6FA5','#A3B8D6','#F78C16','#C9D6E8','#13406A','#43698F','#7EA1C3','#DCE5F0','#EEF2F7','#E3EAF2','#F3F6FA','#EEF0F3','#E2E7EF','#566579','#3E4C5E','#FFFFFF','#FFF','NONE','TRANSPARENT','CURRENTCOLOR'];
/* bancada: palco 1280×720 em escala 1:1 por cima do editor (a mesma do test-s07) */
const LAB=`window.__lab=function(slide,play){ var d=document.getElementById('s7blab'); if(!d){ d=document.createElement('div'); d.id='s7blab'; d.style.cssText='position:fixed;left:0;top:0;width:1280px;height:720px;z-index:99999;background:#fff'; document.body.appendChild(d); }
  d.innerHTML=''; d.style.display='block'; var st=AMRT.renderSlide(slide,{play:!!play}); d.appendChild(st); if(play){ st.classList.remove('am-pre'); void st.offsetWidth; st.classList.add('am-in'); if(d._c) d._c(); d._c=AMRT.runFx(st); } return st; };
  window.__labOff=function(){ var d=document.getElementById('s7blab'); if(d){ if(d._c) d._c(); d.innerHTML=''; d.style.display='none'; } };
  window.__el=function(k,v,dark,sc,data){ var F=AMRT.FX[k], w=F.w*(sc||1), h=F.h*(sc||1), d=JSON.parse(JSON.stringify(F.data)); if(data) Object.keys(data).forEach(function(q){ d[q]=data[q]; }); if(dark) d.panel='white'; return {id:'m',type:'fx',kind:k,variant:v||F.variant,x:(1280-w)/2,y:(720-h)/2,w:w,h:h,data:d,anim:{in:'none'}}; };`;
const PIECES='svg path:not(.vc-sw),.sk-q,.sk-it,.sk-lb,.vc-sl,.vc-pl,.vc-mg,.vc-nt,.bm-b,.jr-h,.jr-c,.jr-l,.jr-dot,.ok-obj,.ok-r,.bs-bd b,.bs-c,.ch-lb,.ch-mk,.ad-s';
const CUT='.sk-q,.vc-sl,.vc-pl,.vc-nt,.bm-b,.jr-h,.jr-c,.jr-l,.ok-obj,.ok-m b,.bs-bd b,.bs-c,.ch-lb,.ad-t,.ad-s';
/* o mesmo detector do test-s07 (sobreposição/transbordamento/corte), com as peças dos modelos B */
async function stageCheck(p, sel){
  return p.evaluate(([sel,PIECES,CUT])=>{
    const st=document.querySelector(sel), sr=st.getBoundingClientRect(), k=1280/sr.width, issues=[], boxes=[];
    const L=r=>({x:(r.left-sr.left)*k,y:(r.top-sr.top)*k,r:(r.right-sr.left)*k,b:(r.bottom-sr.top)*k});
    st.querySelectorAll('.am-el[data-id]').forEach(n=>{
      let u=null; const add=r=>{ if(r.width<1||r.height<1) return; const q=L(r); u=u?{x:Math.min(u.x,q.x),y:Math.min(u.y,q.y),r:Math.max(u.r,q.r),b:Math.max(u.b,q.b)}:q; };
      const walker=document.createTreeWalker(n,NodeFilter.SHOW_TEXT); let t; while((t=walker.nextNode())){ if(!t.textContent.trim()) continue; const rg=document.createRange(); rg.selectNodeContents(t); [...rg.getClientRects()].forEach(add); }
      n.querySelectorAll(PIECES).forEach(e=>add(e.getBoundingClientRect()));
      n.querySelectorAll(CUT).forEach(x=>{ if(x.scrollHeight>x.clientHeight+1||x.scrollWidth>x.clientWidth+1) issues.push('corte em "'+x.textContent.trim().slice(0,24)+'"'); });
      if(!u) return; const nb=L(n.getBoundingClientRect());
      if(u.x<-1||u.y<-1||u.r>1281||u.b>721) issues.push('fora do slide '+JSON.stringify([u.x,u.y,u.r,u.b].map(Math.round)));
      if(u.x<nb.x-14||u.y<nb.y-14||u.r>nb.r+14||u.b>nb.b+14) issues.push('fora da caixa '+JSON.stringify([u.x-nb.x,u.y-nb.y,u.r-nb.r,u.b-nb.b].map(Math.round)));
      boxes.push({id:n.dataset.id,u});
    });
    for(let i=0;i<boxes.length;i++) for(let j=i+1;j<boxes.length;j++){ const a=boxes[i].u,b=boxes[j].u; const w=Math.min(a.r,b.r)-Math.max(a.x,b.x), h=Math.min(a.b,b.b)-Math.max(a.y,b.y); if(w>2&&h>2) issues.push('sobreposição '+boxes[i].id+'×'+boxes[j].id); }
    return issues;
  }, [sel,PIECES,CUT]);
}
/* sobreposição entre textos editáveis de um modelo no palco (ideia do scan do test-s07) */
const overlaps=(p,sel)=>p.evaluate((sel)=>{ const st=document.querySelector(sel), R=[], out=[];
  st.querySelectorAll('[data-e]').forEach(s=>{ if(!s.textContent.trim()) return; const rs=[...s.getClientRects()].filter(r=>r.width>0&&r.height>0); if(!rs.length) return; R.push({s,t:s.textContent.trim().slice(0,20),u:rs.reduce((a,r)=>({l:Math.min(a.l,r.left),t:Math.min(a.t,r.top),r:Math.max(a.r,r.right),b:Math.max(a.b,r.bottom)}),{l:1e9,t:1e9,r:-1e9,b:-1e9})}); });
  for(let i=0;i<R.length;i++) for(let j=i+1;j<R.length;j++){ const a=R[i],b=R[j]; if(a.s.contains(b.s)||b.s.contains(a.s)) continue; const w=Math.min(a.u.r,b.u.r)-Math.max(a.u.l,b.u.l), h=Math.min(a.u.b,b.u.b)-Math.max(a.u.t,b.u.t); if(w>2&&h>2) out.push(a.t+' × '+b.t); }
  return out; },sel);
async function lab(p,k,v,dark,sc,data,wait){ await p.evaluate(([k,v,dark,sc,data,play])=>{ window.__lab({bg:dark?'#002A46':'#fff',els:[window.__el(k,v,dark,sc,data)]}, play); },[k,v||null,!!dark,sc||1,data||null,wait!=null]); await sleep(wait||60); }
(async()=>{
  const b=await chromium.launch();
  const ctx=await b.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
  const p=await page(ctx, FILE+'?nocover', 'ed');
  await p.evaluate(LAB);

  /* ---------- 1. registro dos 7 modelos, presets e ganchos ---------- */
  const reg=await p.evaluate((KINDS)=>KINDS.map(k=>{ const F=AMRT.FX[k]; if(!F) return {k,missing:true}; return {k,model:!!F.model,cat:F.cat,nv:(F.variants||[]).length,labels:(F.variants||[]).every(v=>v[0]&&v[1]&&v[2]&&/^[a-z]+$/.test(v[0])),defOk:(F.variants||[]).some(v=>v[0]===F.variant),size:[F.w,F.h],nf:(F.fields||[]).length,tip:!!F.tip,kw:!!F.kw&&F.kw.length>20,html:typeof F.html==='function',norm:typeof F.norm==='function'}; }),KINDS);
  const pr=await p.evaluate((PRESETS)=>{ const P=AMRT.PRESETS||{}; return {keys:Object.keys(P).sort().join(','), ok:Object.keys(PRESETS).every(k=>P[k]&&P[k].kind===PRESETS[k]&&P[k].name&&P[k].cat&&P[k].kw&&P[k].data&&typeof P[k].data==='object'&&AMRT.FX[P[k].kind].variants.some(v=>v[0]===P[k].variant)), hooks:['matrix','cardgrid','smart'].every(k=>typeof AMRT.FX[k].label==='function'), fns:typeof AMRT.presetOf==='function'&&typeof AMRT.spline==='function', chLabel:typeof AMRT.FX.change.label==='function',
    codecs:{stake:AMRT.FX.stake.fields[0][2], journey:AMRT.FX.journey.fields.map(f=>f[2]).join('|'), bsc:AMRT.FX.bsc.fields.map(f=>f[2]).join('|'), okr:AMRT.FX.okr.fields[1][2], change:AMRT.FX.change.fields[0][2].slice(0,4), vc:AMRT.FX.valuechain.fields.map(f=>f[2]||'text').join('|'), bmc:AMRT.FX.bmc.fields.length},
    sp:(()=>{ const s=AMRT.spline([[0,0],[10,10],[20,0]]); return s.segs.length===2&&/^M0\.0 0\.0C/.test(s.d); })()}; },PRESETS);
  check('S07B-01: os 7 modelos registrados (model:true) nas categorias certas (stake, bmc e bsc em Estratégia; valuechain e change em Processos; journey em Evolução; okr em Indicadores), cada um com 3–4 efeitos com chave, rótulo e descrição, efeito padrão válido, tamanho ≤ 1172×470, campos, dica, palavras-chave e gancho norm; 8 presets (AMRT.PRESETS) sobre matrix / cardgrid / smart com nome, categoria, palavras-chave, dados e efeito válido; ganchos label em matrix, cardgrid, smart e change; AMRT.presetOf e AMRT.spline; codecs: stakeholders rows:t|x:n|y:n|st|tx:n|ty:n, jornada lines|rows:k|*v|lines, BSC rows:p:n|t|rows:a:n|b:n|lines, OKR rows:t|v:n|tg:n|u|c, curva sel:, cadeia lines|lines|texto|rows:n:n|x|texto, canvas 10 campos', reg.every(r=>!r.missing&&r.model&&r.cat===CAT[r.k]&&r.nv>=3&&r.nv<=4&&r.labels&&r.defOk&&r.size[0]<=1172&&r.size[1]<=470&&r.nf>=1&&r.tip&&r.kw&&r.html&&r.norm)&&pr.keys==='ansoff,eisenhower,iceberg,kano,minto,scr,sipoc,w5h2'&&pr.ok&&pr.hooks&&pr.fns&&pr.chLabel&&pr.codecs.stake==='rows:t|x:n|y:n|st|tx:n|ty:n'&&pr.codecs.journey==='lines|rows:k|*v|lines'&&pr.codecs.bsc==='rows:p:n|t|rows:a:n|b:n|lines'&&pr.codecs.okr==='rows:t|v:n|tg:n|u|c'&&pr.codecs.change==='sel:'&&pr.codecs.vc==='lines|lines|text|rows:n:n|x|text'&&pr.codecs.bmc===10&&pr.sp, {reg,pr});

  /* ---------- 2. Biblioteca de modelos: cards dos modelos e presets, chips, prévias só nos visíveis, busca ---------- */
  await p.click('#bModels'); await sleep(900);
  const dr=await p.evaluate(([KINDS,PRESETS])=>{ const cats={}, order=[]; document.querySelectorAll('#modelsBody .dcat').forEach(c=>{ order.push(c.dataset.cat); cats[c.dataset.cat]=[...c.nextElementSibling.querySelectorAll('.fxi')].map(x=>x.dataset.k+(x.dataset.preset?':'+x.dataset.preset:'')); });
    const all=[...document.querySelectorAll('#modelsBody .fxi')], b=document.getElementById('modelsBody').getBoundingClientRect(), vis=all.filter(c=>{ const r=c.getBoundingClientRect(); return r.bottom>b.top-160&&r.top<b.bottom+160; });
    const cards={}; KINDS.forEach(k=>{ const c=document.querySelector('#modelsBody .fxi[data-k='+k+']:not([data-preset])'); cards[k]=c?{pv:!!c.querySelector('.pv .am-stage .fx'), pills:c.querySelectorAll('.vl span').length, name:c.querySelector('.ft b').textContent}:null; });
    const pre={}; Object.keys(PRESETS).forEach(k=>{ const c=document.querySelector('#modelsBody .fxi[data-preset='+k+']'); pre[k]=c?{kind:c.dataset.k, pv:!!c.querySelector('.pv .am-stage .fx'), small:c.querySelector('.ft small').textContent, name:c.querySelector('.ft b').textContent, btn:!!c.querySelector('button[data-ins='+PRESETS[k]+'][data-preset='+k+']'), pills:c.querySelectorAll('.vl span').length, nv:AMRT.FX[c.dataset.k].variants.length, pvPreset:c._slide&&c._slide.els[0].data.preset, pvVar:c._slide&&c._slide.els[0].variant}:null; });
    const chips=[...document.querySelectorAll('#mCats .chip')].map(x=>x.dataset.cat+':'+x.querySelector('small').textContent);
    return {order,cats,cards,pre,n:all.length,stages:all.filter(c=>c.querySelector('.pv .am-stage')).length,live:all.filter(c=>c._live).length,vis:vis.length,visLive:vis.every(c=>c._live),chips,on:(document.querySelector('#mCats .chip.on')||{}).dataset,engineFirst:cats['Matrizes'].indexOf('matrix')<cats['Matrizes'].indexOf('matrix:eisenhower')}; },[KINDS,PRESETS]);
  const mut=await p.evaluate(async()=>{ const seen=new Set(); const o=new MutationObserver(ms=>ms.forEach(m=>{ const c=m.target.closest&&m.target.closest('.fxi'); if(c) seen.add(c); })); o.observe(document.getElementById('modelsBody'),{childList:true,subtree:true,characterData:true}); await new Promise(r=>setTimeout(r,5600)); o.disconnect(); const b=document.getElementById('modelsBody').getBoundingClientRect(); return {n:seen.size, allVis:[...seen].every(c=>{ const r=c.getBoundingClientRect(); return r.bottom>b.top-160&&r.top<b.bottom+160; }), total:document.querySelectorAll('#modelsBody .fxi').length}; });
  check('S07B-02: gaveta Modelos: os 7 modelos nas categorias certas com prévia viva, nome e 3–4 pílulas; 8 cards de preset (data-k = motor, data-preset = chave, prévia já com os dados e o efeito do preset, botão Inserir com data-preset, subtítulo “Preset · <motor>”, pílulas = efeitos do motor) depois dos motores da categoria (Ansoff, SCR e Minto em Estratégia; Eisenhower e Kano em Matrizes; Iceberg, 5W2H e SIPOC em Processos); chips de categoria (#mCats) com a contagem de cards e o 1º aceso; todos os cards têm palco ao abrir, mas só os visíveis (≈6 de 42+) animam e só eles redesenham num ciclo de 5,6 s', KINDS.every(k=>(dr.cats[CAT[k]]||[]).indexOf(k)>=0&&dr.cards[k]&&dr.cards[k].pv&&dr.cards[k].pills>=3&&dr.cards[k].pills<=4)&&Object.keys(PRESETS).every(k=>dr.pre[k]&&dr.pre[k].kind===PRESETS[k]&&dr.pre[k].pv&&dr.pre[k].btn&&/^Preset · /.test(dr.pre[k].small)&&dr.pre[k].pills===dr.pre[k].nv&&dr.pre[k].pvPreset===k&&dr.pre[k].pvVar===AMRT_PV(k))&&['ansoff','scr','minto'].every(k=>dr.cats['Estratégia'].indexOf(PRESETS[k]+':'+k)>=0)&&['eisenhower','kano'].every(k=>dr.cats['Matrizes'].indexOf('matrix:'+k)>=0)&&['iceberg','w5h2','sipoc'].every(k=>dr.cats['Processos'].indexOf(PRESETS[k]+':'+k)>=0)&&dr.engineFirst&&dr.n>=42&&dr.stages===dr.n&&dr.live===dr.vis&&dr.visLive&&dr.live<dr.n&&dr.chips.length===dr.order.length&&dr.chips.every((c,i)=>c===dr.order[i]+':'+dr.cats[dr.order[i]].length)&&dr.on&&dr.on.cat===dr.order[0]&&mut.n>0&&mut.allVis&&mut.n<mut.total, {dr,mut});
  function AMRT_PV(k){ return {ansoff:'quadrants',eisenhower:'quadrants',kano:'quadrants',scr:'number',minto:'level',iceberg:'one',w5h2:'stagger',sipoc:'one'}[k]; }
  await p.click('#mCats .chip[data-cat="Processos"]'); await sleep(1000);
  const jump=await p.evaluate(()=>{ const all=[...document.querySelectorAll('#modelsBody .fxi')], b=document.getElementById('modelsBody').getBoundingClientRect(); const vis=all.filter(c=>{ const r=c.getBoundingClientRect(); return r.bottom>b.top-160&&r.top<b.bottom+160; }); return {on:(document.querySelector('#mCats .chip.on')||{}).dataset.cat, top:document.getElementById('modelsBody').scrollTop, live:all.filter(c=>c._live).map(c=>c.dataset.k+(c.dataset.preset?':'+c.dataset.preset:'')), visLive:vis.every(c=>c._live), offLive:all.filter(c=>c._live&&vis.indexOf(c)<0).length, pdcaTop:document.querySelector('#modelsBody .fxi[data-k=pdca]').getBoundingClientRect().top<b.top+120}; });
  await p.screenshot({path:SH('01-gaveta-processos')});
  const srch={}; for(const [q,exp] of [['ansoff',['matrix:ansoff']],['sipoc',['smart:sipoc']],['okr',['okr']],['canvas',['bmc']],['adkar',['change']],['cadeia de valor',['valuechain']],['stakeholders',['stake']],['eisenhower',['matrix:eisenhower']],['kano',['matrix:kano']],['5w2h',['cardgrid:w5h2']],['minto',['smart:minto']],['iceberg',['smart:iceberg']],['scr',['cardgrid:scr']],['jornada do cliente',['journey']]]){ await p.fill('#mSearch',q); await sleep(250); srch[q]=await p.evaluate(()=>[...document.querySelectorAll('#modelsBody .fxi')].filter(c=>c.style.display!=='none').map(c=>c.dataset.k+(c.dataset.preset?':'+c.dataset.preset:'')).sort()); srch[q+'_ok']=JSON.stringify(srch[q])===JSON.stringify(exp.slice().sort()); }
  await p.fill('#mSearch','scorecard'); await sleep(250); const sc2=await p.evaluate(()=>({vis:[...document.querySelectorAll('#modelsBody .fxi')].filter(c=>c.style.display!=='none').map(c=>c.dataset.k), chips:[...document.querySelectorAll('#mCats .chip')].filter(c=>c.style.display!=='none').map(c=>c.dataset.cat), live:[...document.querySelectorAll('#modelsBody .fxi')].filter(c=>c.style.display!=='none').every(c=>c._live)}));
  await p.fill('#mSearch',''); await sleep(300); await p.click('#bFxClose'); await sleep(300);
  check('S07B-03: o chip “Processos” rola a gaveta até a categoria (PDCA no topo), acende e religa só os cards que entraram na janela (os de fora param); buscas “ansoff”, “sipoc”, “okr”, “canvas”, “adkar”, “cadeia de valor”, “stakeholders”, “eisenhower”, “kano”, “5w2h”, “minto”, “iceberg”, “scr” e “jornada do cliente” acham só o card certo; “scorecard” acha o BSC (e só chips de categorias visíveis ficam), com os resultados animando', jump.on==='Processos'&&jump.top>200&&jump.pdcaTop&&jump.visLive&&jump.offLive===0&&jump.live.indexOf('valuechain')>=0&&Object.keys(srch).filter(k=>/_ok$/.test(k)).every(k=>srch[k])&&sc2.vis.indexOf('bsc')>=0&&sc2.chips.indexOf('Estratégia')>=0&&sc2.chips.indexOf('Riscos')<0&&sc2.live, {jump,srch,sc2});

  /* ---------- 3. inserir cada modelo: elemento, efeito padrão, painel (chips + campos com o codec certo) ---------- */
  const ins={};
  for(const k of KINDS){ await fresh(p); await p.evaluate(k=>AMStudio.insertFx(k),k); await sleep(350);
    ins[k]=await p.evaluate((k)=>{ const e=AMStudio.deck.slides[0].els[0], F=AMRT.FX[k], q=s=>document.querySelector('#props '+s); return {kind:e.kind, v:e.variant, dv:F.variant, panel:e.data.panel, n:AMStudio.deck.slides[0].els.length, name:q('.ph h2').firstChild.textContent, chips:[...document.querySelectorAll('#props [data-var]')].map(x=>x.dataset.var).join(','), vars:F.variants.map(v=>v[0]).join(','), codecs:[...document.querySelectorAll('#props [data-p^="data."]')].map(x=>x.dataset.p.slice(5)+':'+(x.dataset.codec||x.tagName.toLowerCase()+(x.type?'/'+x.type:''))), stage:!!document.querySelector('#wrap .am-stage .am-el .fx'), zoom:q('[data-set=zoom]')&&/\bon\b/.test(q('[data-set=zoom]').className), tip:!!q('.vtip')}; },k);
    if(k==='journey') await p.screenshot({path:SH('02-painel-jornada')}); }
  check('S07B-04: insertFx de cada modelo cria 1 elemento no efeito padrão, sem painel branco em slide claro, renderizado no palco; o painel mostra o nome, os chips de efeito (na ordem do registro), a dica, “Ampliar na apresentação” ligado e os campos com o codec certo (stakeholders: rows + quadrantes lines + eixos; jornada: etapas lines, linhas rows:k|*v, emoção lines; OKR: objetivo, krs rows, rótulo, dono; curva: modo select, etapas lines, posição texto, marcador, adkar rows)', KINDS.every(k=>ins[k].kind===k&&ins[k].v===ins[k].dv&&ins[k].panel==null&&ins[k].n===1&&ins[k].stage&&ins[k].chips===ins[k].vars&&ins[k].zoom&&ins[k].tip&&ins[k].name===AMRT_NAME(k,ins[k].name))&&ins.stake.codecs.join('|')==='items:rows:t|x:n|y:n|st|tx:n|ty:n|q:lines|xlab:input/text|ylab:input/text'&&ins.journey.codecs.join('|')==='stages:lines|rows:rows:k|*v|emo:lines'&&ins.okr.codecs.join('|')==='obj:input/text|krs:rows:t|v:n|tg:n|u|c|eyebrow:input/text|owner:input/text'&&ins.change.codecs.join('|')==='mode:select/select-one|stages:lines|pos:input/text|marker:input/text|adkar:rows:t|v:n'&&ins.change.name==='Curva da mudança', ins);
  function AMRT_NAME(k,n){ return k==='change'?'Curva da mudança':n; }

  /* ---------- 4. presets: inserir pelo botão, nome no painel, arrastar, soltar, dados não compartilhados ---------- */
  await fresh(p); await p.click('#bModels'); await sleep(600);
  await p.evaluate(()=>document.querySelector('#modelsBody button[data-preset=ansoff]').scrollIntoView({block:'center'})); await sleep(400);
  await p.click('#modelsBody button[data-preset=ansoff]'); await sleep(700);
  const pa=await p.evaluate(()=>{ const e=AMStudio.deck.slides[0].els[0]; e.data.q[0]='Mudado'; return {kind:e.kind, v:e.variant, preset:e.data.preset, q:AMRT.PRESETS.ansoff.data.q[0], q0:e.data.q[0], items:e.data.items.length, name:document.querySelector('#props .ph h2').firstChild.textContent, label:AMRT.fxLabel(e), drawer:document.getElementById('drawer').classList.contains('open'), stage:document.querySelectorAll('#wrap .am-stage .mx-q').length}; });
  const pay=await p.evaluate(()=>{ AMStudio.closeMenus(); const out={}; [['sipoc','smart'],['w5h2','cardgrid'],['kano','matrix']].forEach(([k,kind])=>{ const c=document.querySelector('#modelsBody .fxi[data-preset='+k+']'), dt=new DataTransfer(); c.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt})); out[k]=dt.getData('text/plain'); }); const e=document.querySelector('#modelsBody .fxi[data-k=raci]'), dt2=new DataTransfer(); e.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt2})); out.raci=dt2.getData('text/plain'); return out; });
  const drop=await p.evaluate(()=>{ const w=document.getElementById('wrap'), r=w.getBoundingClientRect(), n0=AMStudio.deck.slides[0].els.length; ['amfx:smart:one:sipoc','amfx:matrix::nope','amfx:cardgrid:stagger:minto','amfx:smart::org'].forEach((t,i)=>{ const dt=new DataTransfer(); dt.setData('text/plain',t); w.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt,clientX:r.left+r.width*(.3+i*.1),clientY:r.top+r.height*.5})); }); const e=AMStudio.deck.slides[0].els; return {n0, n:e.length, kinds:e.slice(n0).map(x=>x.kind).join(','), presets:e.slice(n0).map(x=>x.data.preset||'-').join(','), labels:e.slice(n0).map(x=>AMRT.fxLabel(x)).join('|'), sipoc:e[n0].data.layout+'/'+e[n0].data.items.length+'/'+e[n0].data.items[0].t, minto:e[n0+2].data.cards.length}; });
  await p.screenshot({path:SH('03-presets-inseridos')});
  check('S07B-05: o botão Inserir do card Ansoff cria uma matriz 2×2 com os quadrantes de Ansoff, o efeito “Quadrante a quadrante” e data.preset = “ansoff”; o painel e AMRT.fxLabel dizem “Matriz de Ansoff”; a gaveta fecha; os dados do preset são clonados (mudar o elemento não muda AMRT.PRESETS); arrastar um card de preset dá “amfx:<motor>:<efeito>:<preset>” (SIPOC, 5W2H, Kano) e um motor dá “amfx:raci”; soltar “amfx:smart:one:sipoc” cria o SmartArt processo com 13 itens e o rótulo “SIPOC”, um preset inexistente cria o motor puro (sem preset), um preset de outro motor (minto em cardgrid) cai no motor puro e “amfx:smart::org” continua sendo o layout (S06)', pa.kind==='matrix'&&pa.v==='quadrants'&&pa.preset==='ansoff'&&pa.q==='Desenvolvimento de mercado'&&pa.q0==='Mudado'&&pa.items===4&&pa.name==='Matriz de Ansoff'&&pa.label==='Matriz de Ansoff'&&!pa.drawer&&pa.stage>=4&&pay.sipoc==='amfx:smart:one:sipoc'&&pay.w5h2==='amfx:cardgrid:stagger:w5h2'&&pay.kano==='amfx:matrix:quadrants:kano'&&pay.raci==='amfx:raci'&&drop.n===drop.n0+4&&drop.kinds==='smart,matrix,cardgrid,smart'&&drop.presets==='sipoc,-,-,-'&&drop.labels==='SIPOC|Matriz de priorização (2×2)|Grade de cards|SmartArt · Hierarquia'&&drop.sipoc==='process/13/Fornecedores'&&drop.minto===4, {pa,pay,drop});

  /* ---------- 5. stakeholders e cadeia de valor: peças e efeitos ---------- */
  const sk=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('stake',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=(n,ps)=>getComputedStyle(n,ps||null);
    let st=await run('drop',null,60); const IT=[...st.querySelectorAll('.sk-it')]; out.q=[...st.querySelectorAll('.sk-q')].map(q=>q.textContent).join('|'); out.n=IT.length; out.st=IT.map(i=>i.querySelector('.sk-d').className.replace('sk-d ','')).join(','); out.badges=st.querySelectorAll('.sk-plot .sk-d b').length; out.g=IT.map(i=>i.dataset.g).join(''); out.lbs=st.querySelectorAll('.sk-lb').length; out.ar=st.querySelectorAll('.sk-ar').length; out.gh=[st.querySelectorAll('.sk-gh').length, cs(st.querySelector('.sk-gh')).display]; out.leg=[...st.querySelectorAll('.sk-leg>span')].map(s=>s.textContent).join(','); out.legBadge=st.querySelectorAll('.sk-leg .sk-d b').length; out.drop={it:cs(IT[1]).animationName, d:cs(IT[1]).animationDelay, q:cs(st.querySelector('.sk-q')).animationName, ar:cs(st.querySelector('.sk-ar')).animationName, ard:cs(st.querySelector('.sk-ar')).animationDelay, ring:cs(IT[2].querySelector('.sk-d')).boxShadow}; out.axes=st.querySelector('.sk-x span').textContent+'/'+st.querySelector('.sk-y').textContent;
    st=await run('move',null,2600); out.move={gh:cs(st.querySelector('.sk-gh')).display, a:cs(st.querySelector('.sk-gh')).animationName, op:+cs(st.querySelector('.sk-gh')).opacity};
    st=await run('quadrants',null,60); out.quad={q:cs(st.querySelector('.sk-q')).animationName, it:cs(st.querySelector('.sk-it')).animationName, d:cs(st.querySelector('.sk-it')).animationDelay};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxsk').dataset.cycle, active:st.querySelector('.fxsk').classList.contains('cy-active'), on:st.querySelectorAll('.cy-on').length};
    st=await run('drop',{items:[{t:'Só um',x:50,y:50,st:'zzz'},{t:'',x:0,y:0},{t:'Meta',x:10,y:10,st:'a',tx:90,ty:90}]},60); out.alt={n:st.querySelectorAll('.sk-it').length, st:st.querySelector('.sk-it .sk-d').className, ar:st.querySelectorAll('.sk-ar').length, arL:st.querySelectorAll('.sk-ar.l').length};
    return out; });
  await p.screenshot({path:SH('04-stake-move')}); await p.evaluate(()=>window.__labOff());
  check('S07B-06: stakeholders: quadrantes Manter satisfeito / Gerenciar de perto / Monitorar / Manter informado, 7 chips (2 apoiadores navy, 3 neutros, 2 resistentes com “!”), grupos por quadrante 1013233, 7 rótulos, 2 setas tracejadas e 2 anéis-fantasma só em “Rumo à posição desejada” (opacidade 0,45, m8Ghost), legenda Apoiador / Neutro / Resistente (com o “!”); “Pousando no mapa” (amDropC, 2º chip a 0,76 s, setas m8WipeR a 1,55 s, anel laranja no resistente); “Quadrante a quadrante” (amZoom, 1º chip amPopC a 0,72 s); “Foco percorrendo” acende um quadrante com os seus chips; postura inválida vira neutro, linha vazia some, seta para a direita sem .l', sk.q==='Manter satisfeito|Gerenciar de perto|Monitorar|Manter informado'&&sk.n===7&&sk.st==='sk-sa,sk-sn,sk-sr,sk-sr,sk-sn,sk-sa,sk-sn'&&sk.badges===2&&sk.g==='1013232'&&sk.lbs===7&&sk.ar===2&&sk.gh[0]===2&&sk.gh[1]==='none'&&sk.leg==='Apoiador,Neutro,!Resistente'&&sk.legBadge===1&&sk.drop.it==='amDropC'&&sk.drop.d==='0.76s'&&sk.drop.q==='amFade'&&sk.drop.ar==='m8WipeR'&&sk.drop.ard==='1.55s'&&/247, 140, 22/.test(sk.drop.ring)&&/Interesse/.test(sk.axes)&&/Poder/.test(sk.axes)&&sk.move.gh==='block'&&sk.move.a==='m8Ghost'&&Math.abs(sk.move.op-.45)<.02&&sk.quad.q==='amZoom'&&sk.quad.it==='amPopC'&&sk.quad.d==='0.72s'&&sk.focus.cycle==='g'&&sk.focus.active&&sk.focus.on>=3&&sk.alt.n===2&&/sk-sn/.test(sk.alt.st)&&sk.alt.ar===1&&sk.alt.arL===0, sk);
  const vc=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('valuechain',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('build',null,60); out.n={s:st.querySelectorAll('.vc-s').length, p:st.querySelectorAll('.vc-p').length, hl:[...st.querySelectorAll('.vc-s,.vc-p')].map(x=>x.classList.contains('hl')?1:0).join(''), sl:st.querySelectorAll('.vc-sl').length, pl:st.querySelectorAll('.vc-pl').length, badges:[...st.querySelectorAll('.vc-sl .vc-n,.vc-pl .vc-n')].map(b=>b.textContent).join(','), notes:[...st.querySelectorAll('.vc-nt')].map(n=>n.dataset.g+':'+n.textContent.slice(0,3)).join(','), sw:st.querySelectorAll('.vc-sw').length, g:[...st.querySelectorAll('[data-g]')].map(x=>x.dataset.g).filter((x,i,a)=>a.indexOf(x)===i).join('')}; out.mg={t:st.querySelector('.vc-mg').textContent, ang:cs(st.querySelector('.vc-mg')).getPropertyValue('--ang').trim(), tf:cs(st.querySelector('.vc-mg')).transform!=='none'}; const last=[...st.querySelectorAll('.vc-p')].pop().getAttribute('d'), first=st.querySelector('.vc-p').getAttribute('d'); out.shape={lastPts:(last.match(/[ML]/g)||[]).length, firstPts:(first.match(/[ML]/g)||[]).length, lastSlant:!/L[\d.]+ [\d.]+L[\d.]+ [\d.]+Z$/.test('')&&last.split('L').length>=5}; out.build={s1:cs(st.querySelectorAll('.vc-s')[1]).animationDelay, sA:cs(st.querySelector('.vc-s')).animationName, p0:cs(st.querySelector('.vc-p')).animationDelay, pA:cs(st.querySelector('.vc-p')).animationName, mg:cs(st.querySelector('.vc-mg')).animationDelay, nt:cs(st.querySelector('.vc-nt')).animationDelay, hlFill:cs(st.querySelector('.vc-p.hl')).fill, sFill:cs(st.querySelector('.vc-s')).fill};
    st=await run('flow',null,2500); const sw=st.querySelector('.vc-sw'); out.flow={n:st.querySelectorAll('.vc-sw').length, inG:sw.parentElement.tagName.toLowerCase()==='g'&&/url\(#/.test(sw.parentElement.getAttribute('clip-path')), a:cs(sw).animationName, d:cs(sw).animationDelay, x0:sw.getBoundingClientRect().x}; await new Promise(r=>setTimeout(r,700)); out.flow.x1=sw.getBoundingClientRect().x; out.flow.moved=out.flow.x1-out.flow.x0>20;
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxvc').dataset.cycle, on:st.querySelectorAll('.cy-on').length, active:st.querySelector('.fxvc').classList.contains('cy-active')};
    st=await run('build',{support:['A','B'],primary:['Um','Dois','Três'],hl:'9, 2, x',notes:[{n:9,x:'fora'},{n:2,x:''},{n:1,x:'ok'}]},60); out.alt={s:st.querySelectorAll('.vc-s').length, p:st.querySelectorAll('.vc-p').length, hl:[...st.querySelectorAll('.vc-s,.vc-p')].map(x=>x.classList.contains('hl')?1:0).join(''), notes:st.querySelectorAll('.vc-nt').length, badge:st.querySelectorAll('.vc-n').length, nts:!!st.querySelector('.vc-nts')};
    st=await run('build',{notes:[]},60); out.noNotes={nts:!!st.querySelector('.vc-nts'), h:Math.round(st.querySelector('.vc-p').getBoundingClientRect().bottom-st.querySelector('.vc-s').getBoundingClientRect().top)};
    return out; });
  await p.screenshot({path:SH('05-cadeia-flow')}); await p.evaluate(()=>window.__labOff());
  check('S07B-07: cadeia de valor: 4 faixas de apoio + 5 atividades primárias, destaques nas posições 2 e 6 (laranja), rótulos com os números das notas (2, 6) e 2 notas no rodapé ligadas aos grupos 1 e 5, 9 grupos (data-g 0–8), “Margem” rotacionada ao longo da rampa superior (--ang), a última atividade com a borda inclinada (5 vértices) e as demais em chevron (6); “Montando a cadeia” (faixas amWipe, 2ª a 0,14 s; chevrons amWipe a partir de 0,81 s; margem a 1,91 s; notas a 2,11 s; apoio em gelo e destaque laranja); “Fluxo de valor” (varredura .vc-sw dentro de um grupo recortado pelos chevrons, m8Flow a partir de 2,31 s, deslocando-se); “Foco percorrendo” acende uma atividade; destaque inválido (9, x) e nota fora da faixa ou vazia são ignorados; sem notas a cadeia ocupa a altura toda', vc.n.s===4&&vc.n.p===5&&vc.n.hl==='010001000'&&vc.n.sl===4&&vc.n.pl===5&&vc.n.badges==='2,6'&&vc.n.notes==='1:2Ac,5:6Au'&&vc.n.sw===0&&vc.n.g==='012345678'&&vc.mg.t==='Margem'&&/deg$/.test(vc.mg.ang)&&vc.mg.tf&&vc.shape.lastPts===5&&vc.shape.firstPts===5&&vc.build.s1==='0.14s'&&vc.build.sA==='amWipe'&&vc.build.p0==='0.81s'&&vc.build.pA==='amWipe'&&vc.build.mg==='1.91s'&&vc.build.nt==='2.11s'&&vc.build.hlFill==='rgb(247, 140, 22)'&&vc.build.sFill==='rgb(227, 234, 242)'&&vc.flow.n===1&&vc.flow.inG&&vc.flow.a==='m8Flow'&&vc.flow.d==='2.31s'&&vc.flow.moved&&vc.focus.cycle==='g'&&vc.focus.active&&vc.focus.on>=2&&vc.alt.s===2&&vc.alt.p===3&&vc.alt.hl==='01000'&&vc.alt.notes===1&&vc.alt.badge===2&&vc.alt.nts&&!vc.noNotes.nts&&vc.noNotes.h>=415, vc);

  /* ---------- 6. canvas, jornada, OKR ---------- */
  const bm=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('bmc',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=(n,ps)=>getComputedStyle(n,ps||null);
    let st=await run('blocks',null,60); const B=[...st.querySelectorAll('.bm-b')]; out.n=B.length; out.titles=B.map(b=>b.querySelector('b').textContent).join('|'); out.areas=B.map(b=>b.style.gridArea).join(' '); out.lis=B.map(b=>b.querySelectorAll('li').length).join(''); out.vp={bar:cs(st.querySelector('.bm-vp'),'::before').backgroundColor, other:cs(st.querySelector('.bm-kp'),'::before').backgroundColor}; out.blocks={cs:cs(st.querySelector('.bm-cs')).animationDelay, vp:cs(st.querySelector('.bm-vp')).animationDelay, cost:cs(st.querySelector('.bm-cost')).animationDelay, a:cs(st.querySelector('.bm-cs')).animationName, li:cs(st.querySelector('.bm-vp li')).animationDelay}; out.fs0=parseFloat(cs(st.querySelector('.fxbm')).fontSize); out.g=B.map(b=>b.dataset.g).join('');
    st=await run('sides',null,60); out.sides={vp:cs(st.querySelector('.bm-vp')).animationDelay, kp:cs(st.querySelector('.bm-kp')).animationDelay, a:cs(st.querySelector('.bm-vp')).animationName};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxbm').dataset.cycle, on:st.querySelectorAll('.cy-on').length};
    st=await run('blocks',{kp:Array.from({length:8},(_,i)=>'Parceiro estratégico número '+(i+1)+' com descrição longa'),vp:Array.from({length:8},(_,i)=>'Proposta '+(i+1)+' detalhada em várias palavras para testar')},60); out.fs1=parseFloat(cs(st.querySelector('.fxbm')).fontSize); out.cut=[...st.querySelectorAll('.bm-b')].filter(b=>b.scrollHeight>b.clientHeight+1).length; out.lis1=st.querySelectorAll('.bm-kp li').length;
    st=await run('blocks',{titles:['A','B','C','D','E','F','G','H','I','J'],kp:'x;y',vp:[]},60); out.t2=[...st.querySelectorAll('.bm-b b')].map(b=>b.textContent).join(''); out.vpEmpty=st.querySelector('.bm-vp ul').children.length;
    return out; });
  await p.evaluate(()=>window.__labOff());
  check('S07B-08: canvas: 9 blocos nas áreas da grade (parcerias / atividades / recursos / proposta / relacionamento / canais / segmentos / custos / receitas), com os títulos clássicos e 2–3 tópicos, barra superior laranja só na proposta de valor, grupos 0–8; “Contando a história” (amRise: segmentos a 0 s, proposta a 0,25 s, custos a 2 s; tópicos em cascata); “Valor, depois eficiência” (proposta a 0 s, parcerias a 1,54 s); “Foco percorrendo”; 8 tópicos longos reduzem a fonte do canvas sem cortar bloco; títulos próprios (9 de 10 linhas) e lista em texto “x;y” funcionam; proposta vazia não quebra', bm.n===9&&bm.titles==='Parcerias-chave|Atividades-chave|Recursos-chave|Proposta de valor|Relacionamento com clientes|Canais|Segmentos de clientes|Estrutura de custos|Fontes de receita'&&bm.areas==='1 / 1 / 3 / 3 1 / 3 / 2 / 5 2 / 3 / 3 / 5 1 / 5 / 3 / 7 1 / 7 / 2 / 9 2 / 7 / 3 / 9 1 / 9 / 3 / 11 3 / 1 / 4 / 6 3 / 6 / 4 / 11'&&bm.lis==='222322233'&&bm.vp.bar==='rgb(247, 140, 22)'&&bm.vp.other==='rgb(201, 214, 232)'&&bm.blocks.cs==='0s'&&bm.blocks.vp==='0.25s'&&bm.blocks.cost==='2s'&&bm.blocks.a==='amRise'&&bm.blocks.li==='0.47s'&&bm.g==='012345678'&&bm.sides.vp==='0s'&&bm.sides.kp==='1.54s'&&bm.sides.a==='amFade'&&bm.focus.cycle==='g'&&bm.focus.on===1&&bm.fs1<bm.fs0&&bm.cut===0&&bm.lis1===8&&bm.t2==='ABCDEFGHI'&&bm.vpEmpty===0, bm);
  const jr=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('journey',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=(n,ps)=>getComputedStyle(n,ps||null);
    let st=await run('walk',null,60); out.n={h:st.querySelectorAll('.jr-h').length, c:st.querySelectorAll('.jr-c').length, pain:st.querySelectorAll('.jr-pain').length, l:[...st.querySelectorAll('.jr-l')].map(l=>l.textContent.trim()).filter(Boolean).join('|'), dots:[...st.querySelectorAll('.jr-dot')].map(d=>d.className.replace('jr-dot','').trim()||'-').join(','), av:st.querySelectorAll('.jr-av').length, end:st.querySelectorAll('.jr-av.end').length, cols:cs(st.querySelector('.fxjr')).gridTemplateColumns.split(' ').length, pm:[...st.querySelectorAll('.jr-pm')].map(x=>x.textContent).join('')}; const cv=st.querySelector('.jr-cv').getAttribute('d'), ar=st.querySelector('.jr-ar').getAttribute('d'); out.curve={segs:(cv.match(/C/g)||[]).length, m:/^M/.test(cv), area:/ 50L[\d.]+ 50Z$/.test(ar)}; out.walk={h2:cs(st.querySelectorAll('.jr-h')[2]).animationDelay, cv:cs(st.querySelector('.jr-cv')).animationName, cvDur:cs(st.querySelector('.jr-cv')).animationDuration, cvD:cs(st.querySelector('.jr-cv')).animationDelay, av0:cs(st.querySelector('.jr-av')).animationName, avD:cs(st.querySelector('.jr-av')).animationDelay, end:cs(st.querySelector('.jr-av.end')).animationDelay, disp:cs(st.querySelector('.jr-av')).display, painDot:cs(st.querySelector('.jr-pain'),'::before').backgroundColor};
    st=await run('draw',null,60); out.draw={cv:cs(st.querySelector('.jr-cv')).animationName, dur:cs(st.querySelector('.jr-cv')).animationDuration, d2:cs(st.querySelectorAll('.jr-dot')[2]).animationDelay, dot:cs(st.querySelector('.jr-dot')).animationName, pain:cs(st.querySelector('.jr-pain'),'::before').animationName, av:st.querySelectorAll('.jr-av').length, avDisp:st.querySelector('.jr-av')?cs(st.querySelector('.jr-av')).display:'none'};
    st=await run('stages',null,60); out.stages={h3:cs(st.querySelectorAll('.jr-h')[3]).animationDelay, a:cs(st.querySelectorAll('.jr-h')[3]).animationName, cvDur:cs(st.querySelector('.jr-cv')).animationDuration};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxjr').dataset.cycle, on:st.querySelectorAll('.cy-on').length, active:st.querySelector('.fxjr').classList.contains('cy-active')};
    st=await run('walk',{stages:['Só uma'],emo:[3],rows:[{k:'Dores',v:['x']}]},60); out.one={dots:st.querySelectorAll('.jr-dot').length, cv:st.querySelectorAll('.jr-cv').length, av:st.querySelectorAll('.jr-av').length, top:st.querySelector('.jr-dot').style.top, rows:st.querySelectorAll('.jr-c').length};
    st=await run('draw',{stages:['A','B','C','D','E','F','G','H'],emo:[2,1,0,-1,-2,-1,1,2],rows:[{k:'Ações do cliente',v:Array(8).fill('Faz algo bem detalhado nesta etapa da jornada')},{k:'Pontos de contato',v:Array(8).fill('Site, app, loja')},{k:'Dores',v:Array(8).fill('Uma dor relevante aqui')},{k:'Oportunidades',v:Array(8).fill('Melhoria proposta')},{k:'KPIs',v:Array(8).fill('NPS 62')},{k:'Donos',v:Array(8).fill('Marketing')}]},60); out.big={h:st.querySelectorAll('.jr-h').length, c:st.querySelectorAll('.jr-c').length, cut:[...st.querySelectorAll('.jr-c,.jr-l,.jr-h')].filter(x=>x.scrollHeight>x.clientHeight+1||x.scrollWidth>x.clientWidth+1).length, fs:parseFloat(cs(st.querySelector('.fxjr')).fontSize)};
    return out; });
  await p.screenshot({path:SH('06-jornada-8etapas')}); await p.evaluate(()=>window.__labOff());
  check('S07B-09: jornada: 6 etapas numeradas, 4 linhas × 6 células (a linha “Dores” com marcador laranja), rótulos Ações / Pontos de contato / Emoção / Dores / Oportunidades, 7 colunas de grade, pontos hi / neutro / hi / hi / lo / hi, curva suave de 5 segmentos com a área fechada na linha neutra, marcadores + e −; “Cliente caminhando” (colunas a cada 0,8 s — 3ª a 1,9 s; curva amDraw de 4 s a partir de 0,7 s; 5 avatares de trecho m8Walk + 1 final a 4,7 s, visíveis só nesta variante); “Curva desenhando” (amDraw 1,6 s; 3º ponto amPopC a 1,04 s; dores pulsam m8Pain; sem avatares); “Etapa a etapa” (4ª coluna amRise a 1,05 s; curva em 2,1 s); “Foco percorrendo” acende uma coluna inteira; uma etapa só: 1 ponto (emoção com clamp em +2 = topo 12 %), sem curva, 1 avatar final; 8 etapas × 6 linhas cabem sem corte com a fonte reduzida', jr.n.h===6&&jr.n.c===24&&jr.n.pain===6&&jr.n.l==='Ações|Pontos de contato|Emoção|Dores|Oportunidades'&&jr.n.dots==='hi,-,hi,hi,lo,hi'&&jr.n.av===6&&jr.n.end===1&&jr.n.cols===7&&jr.n.pm==='+−'&&jr.curve.segs===5&&jr.curve.m&&jr.curve.area&&jr.walk.h2==='1.9s'&&jr.walk.cv==='amDraw'&&jr.walk.cvDur==='4s'&&jr.walk.cvD==='0.7s'&&/m8Walk/.test(jr.walk.av0)&&jr.walk.avD.indexOf('0.7s')===0&&jr.walk.end==='4.7s'&&jr.walk.disp==='flex'&&jr.walk.painDot==='rgb(247, 140, 22)'&&jr.draw.cv==='amDraw'&&jr.draw.dur==='1.6s'&&jr.draw.d2==='1.04s'&&jr.draw.dot==='amPopC'&&jr.draw.pain==='m8Pain'&&jr.draw.av===0&&jr.stages.h3==='1.05s'&&jr.stages.a==='amRise'&&jr.stages.cvDur==='2.1s'&&jr.focus.cycle==='g'&&jr.focus.active&&jr.focus.on===6&&jr.one.dots===1&&jr.one.cv===0&&jr.one.av===1&&/^12/.test(jr.one.top)&&jr.one.rows===1&&jr.big.h===8&&jr.big.c===48&&jr.big.cut===0&&jr.big.fs<14, jr);
  const ok=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('okr',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('cascade',null,60); const R=[...st.querySelectorAll('.ok-r')]; out.n=R.length; out.badges=R.map(r=>r.querySelector('.ok-n').textContent).join(','); out.bars=R.map(r=>r.querySelector('.ok-b').style.width).join(','); out.conf=R.map(r=>r.querySelector('.ok-c').className.replace('ok-c ','')+':'+r.querySelector('.ok-c').textContent).join(','); out.vals=R.map(r=>r.querySelector('.ok-v').textContent.replace(/\s+/g,' ')).join('|'); out.card={eye:st.querySelector('.ok-obj small').textContent, bg:cs(st.querySelector('.ok-obj')).backgroundColor, eyeCol:cs(st.querySelector('.ok-obj small')).color, own:st.querySelector('.ok-obj > span').textContent}; out.counts=st.querySelectorAll('[data-count]').length; out.cascade={card:cs(st.querySelector('.ok-obj')).animationName, r2:cs(R[2]).animationDelay, rA:cs(R[2]).animationName, b2:cs(R[2].querySelector('.ok-b')).animationDelay, bA:cs(R[2].querySelector('.ok-b')).animationName}; out.dots={o:cs(st.querySelector('.c-o i')).backgroundColor, r:cs(st.querySelector('.c-r i')).backgroundColor, c:cs(st.querySelector('.c-c i')).backgroundColor};
    st=await run('fill',null,60); out.fill={counts:st.querySelectorAll('[data-count]').length, b:cs(st.querySelector('.ok-b')).animationName, dur:cs(st.querySelector('.ok-b')).animationDuration, d:cs(st.querySelector('.ok-b')).animationDelay, v0:st.querySelector('.ok-v span').textContent}; await new Promise(r=>setTimeout(r,2300)); out.fill.v1=st.querySelector('.ok-v span').textContent;
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxok').dataset.cycle, on:st.querySelectorAll('.cy-on').length, dim:+cs(st.querySelector('.ok-r:not(.cy-on)')).opacity};
    st=await run('cascade',{obj:'Ser reconhecido pelos clientes como o parceiro mais confiável do setor em todo o território nacional até o fim de 2027',owner:'',krs:[{t:'Sem meta',v:5,tg:0,u:'',c:'xyz'},{t:'Acima da meta',v:120,tg:100,u:'%',c:'OK'}]},60); out.alt={bars:[...st.querySelectorAll('.ok-b')].map(b=>b.style.width).join(','), conf:[...st.querySelectorAll('.ok-c')].map(c=>c.className.replace('ok-c ','')).join(','), own:st.querySelectorAll('.ok-obj > span').length, cut:st.querySelector('.ok-obj').scrollHeight>st.querySelector('.ok-obj').clientHeight+1};
    return out; });
  await p.evaluate(()=>window.__labOff());
  check('S07B-10: OKR: card navy do objetivo com rótulo laranja “Objetivo” e a linha de apoio; 4 resultados-chave KR1–KR4 com barras realizado ÷ meta (85 / 83,5 / 71,1 / 100 %), valores “51 / 60 pts”… e confiança No caminho (navy) / Em risco (aço) / Crítico (laranja); “Em cascata” (card amLeft, 3ª linha amRise a 0,76 s, barra amBar a 1,06 s, sem contadores); “Barras e contadores” (4 contadores que partem de 0 e chegam a 51; barras amBar de 1,3 s a 0,25 s); “Foco percorrendo” (uma linha acesa, as outras a 0,3); meta 0 = barra vazia, realizado acima da meta = 100 %, confiança desconhecida = sem status, “OK” em maiúsculas vale, sem dono some a linha de apoio e um objetivo de 112 letras não corta o card', ok.n===4&&ok.badges==='KR1,KR2,KR3,KR4'&&ok.bars==='85%,83.5%,71.1%,100%'&&ok.conf==='c-o:No caminho,c-r:Em risco,c-c:Crítico,c-o:No caminho'&&ok.vals==='51 / 60 pts|71 / 85 %|64 / 90 %|100 / 100 %'&&ok.card.eye==='Objetivo'&&ok.card.bg==='rgb(0, 42, 70)'&&ok.card.eyeCol==='rgb(247, 140, 22)'&&/4º tri 2026/.test(ok.card.own)&&ok.counts===0&&ok.cascade.card==='amLeft'&&ok.cascade.r2==='0.76s'&&ok.cascade.rA==='amRise'&&ok.cascade.b2==='1.06s'&&ok.cascade.bA==='amBar'&&ok.dots.o==='rgb(0, 42, 70)'&&ok.dots.r==='rgb(74, 111, 165)'&&ok.dots.c==='rgb(247, 140, 22)'&&ok.fill.counts===4&&ok.fill.b==='amBar'&&ok.fill.dur==='1.3s'&&ok.fill.d==='0.25s'&&ok.fill.v0==='0'&&ok.fill.v1==='51'&&ok.focus.cycle==='g'&&ok.focus.on===1&&ok.focus.dim<.4&&ok.alt.bars==='0%,100%'&&ok.alt.conf==='c-n,c-o'&&ok.alt.own===0&&!ok.alt.cut, ok);

  /* ---------- 7. BSC e curva da mudança / ADKAR ---------- */
  const bs=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('bsc',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('bottomup',null,60); const C=[...st.querySelectorAll('.bs-c')], A=[...st.querySelectorAll('.bs-a')]; out.n={bands:st.querySelectorAll('.bs-bd').length, alt:st.querySelectorAll('.bs-bd.alt').length, cards:C.length, nums:C.map(c=>c.querySelector('i').textContent).join(''), tones:C.map(c=>c.className.replace('bs-c ','')).join(','), g:C.map(c=>c.dataset.g).join(''), links:A.length, srcBands:A.map(a=>a.dataset.g).join(''), shapes:A.map(a=>a.querySelector('.bs-l').getAttribute('d').replace(/[\d.]+/g,'')).join(' '), heads:st.querySelectorAll('.bs-h').length, labels:[...st.querySelectorAll('.bs-bd b')].map(b=>b.textContent).join('|')}; out.bu={b0:cs(st.querySelectorAll('.bs-bd')[0]).animationDelay, b3:cs(st.querySelectorAll('.bs-bd')[3]).animationDelay, c6:cs(C[6]).animationDelay, cA:cs(C[6]).animationName, l0:cs(A[0].querySelector('.bs-l')).animationDelay, l1:cs(A[1].querySelector('.bs-l')).animationDelay, lA:cs(A[0].querySelector('.bs-l')).animationName, h0:cs(A[0].querySelector('.bs-h')).animationDelay, col:cs(C[0]).backgroundColor, col3:cs(C[6]).backgroundColor};
    st=await run('perspectives',null,60); out.pe={b0:cs(st.querySelectorAll('.bs-bd')[0]).animationDelay, b3:cs(st.querySelectorAll('.bs-bd')[3]).animationDelay};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxbs').dataset.cycle, on:st.querySelectorAll('.cy-on').length, active:st.querySelector('.fxbs').classList.contains('cy-active')};
    st=await run('perspectives',{persp:['A','B','C','D','E'],objs:[{p:1,t:'Um'},{p:1,t:'Dois'},{p:3,t:'Três'},{p:9,t:'Quatro'},{p:0,t:'Cinco'},{p:2,t:''}],links:[{a:1,b:2},{a:2,b:1},{a:3,b:1},{a:1,b:3},{a:1,b:1},{a:7,b:1},{a:1,b:6}]},60); const A2=[...st.querySelectorAll('.bs-a')]; out.alt={bands:st.querySelectorAll('.bs-bd').length, cards:st.querySelectorAll('.bs-c').length, nums:[...st.querySelectorAll('.bs-c i')].map(i=>i.textContent).join(','), g:[...st.querySelectorAll('.bs-c')].map(c=>c.dataset.g).join(''), links:A2.length, shapes:A2.map(a=>a.querySelector('.bs-l').getAttribute('d').replace(/[\d.]+/g,'')).join(' '), tones:[...st.querySelectorAll('.bs-c')].map(c=>c.className.replace('bs-c ','')).join(',')};
    return out; });
  await p.screenshot({path:SH('07-bsc')}); await p.evaluate(()=>window.__labOff());
  check('S07B-11: BSC: 4 perspectivas (2 em gelo alternado) Financeira / Clientes / Processos internos / Aprendizado e crescimento, 8 objetivos numerados 1–8 em tons navy → aço → aço claro → gelo (l0–l3), grupos por faixa 00112233, 7 relações desenhadas de baixo para cima (faixas de origem 3322111) em cotovelo vertical (M V H V) com ponta; “De baixo para cima” (faixa de baixo a 0 s, Financeira a 1,35 s, 7º card amRise a 0,12 s, setas amDraw a 1,8 s e 1,98 s, pontas a 2,22 s); “Perspectiva a perspectiva” (Financeira a 0 s, última a 1,35 s); “Foco percorrendo” acende uma perspectiva com os seus objetivos; dados alternativos: 5 perspectivas, perspectiva fora da faixa cai na última / primeira, objetivo vazio some mas mantém a numeração (1,2,5,3,4 na ordem das faixas), relações na mesma faixa viram setas horizontais (M H), as de baixo para cima primeiro, relação de um objetivo para ele mesmo ou para número inexistente é ignorada', bs.n.bands===4&&bs.n.alt===2&&bs.n.cards===8&&bs.n.nums==='12345678'&&bs.n.tones==='l0,l0,l1,l1,l2,l2,l3,l3'&&bs.n.g==='00112233'&&bs.n.links===7&&bs.n.srcBands==='3322111'&&bs.n.shapes==='M VHV M VHV M VHV M VHV M VHV M VHV M VHV'&&bs.n.heads===7&&bs.n.labels==='Financeira|Clientes|Processos internos|Aprendizado e crescimento'&&bs.bu.b0==='1.35s'&&bs.bu.b3==='0s'&&bs.bu.c6==='0.12s'&&bs.bu.cA==='amRise'&&bs.bu.l0==='1.8s'&&bs.bu.l1==='1.98s'&&bs.bu.lA==='amDraw'&&bs.bu.h0==='2.22s'&&bs.bu.col==='rgb(0, 42, 70)'&&bs.bu.col3==='rgb(238, 242, 247)'&&bs.pe.b0==='0s'&&bs.pe.b3==='1.35s'&&bs.focus.cycle==='g'&&bs.focus.active&&bs.focus.on===3&&bs.alt.bands===5&&bs.alt.cards===5&&bs.alt.nums==='1,2,5,3,4'&&bs.alt.g==='00024'&&bs.alt.links===4&&bs.alt.shapes==='M VHV M H M VHV M H'&&bs.alt.tones==='l0,l0,l0,l2,l3', bs);
  const ch=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('change',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7blab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('draw',null,60); const L=[...st.querySelectorAll('.ch-lb')]; out.n={dots:st.querySelectorAll('.ch-dot').length, lbs:L.map(l=>l.className.replace('ch-lb','').trim()||'-').join(','), txt:L.map(l=>l.textContent).join('|'), mk:st.querySelector('.ch-mk span').textContent, mkDn:st.querySelector('.ch-mk').classList.contains('dn'), tr:st.querySelectorAll('.ch-tr').length, cv:(st.querySelector('.ch-cv').getAttribute('d').match(/C/g)||[]).length, axes:st.querySelector('.ch-y').textContent+'/'+st.querySelector('.ch-x').textContent}; out.draw={cv:cs(st.querySelector('.ch-cv')).animationName, dur:cs(st.querySelector('.ch-cv')).animationDuration, d3:cs(st.querySelectorAll('.ch-dot')[3]).animationDelay, l3:cs(L[3]).animationDelay, mk:cs(st.querySelector('.ch-mk')).animationDelay, dotA:cs(st.querySelector('.ch-dot')).animationName}; const mk=st.querySelector('.ch-mk').getBoundingClientRect(), d3=st.querySelectorAll('.ch-dot')[3].getBoundingClientRect(), d4=st.querySelectorAll('.ch-dot')[4].getBoundingClientRect(); out.mkPos=mk.x>d3.x&&mk.x<d4.x&&mk.y<d3.y&&mk.y>d4.y;
    st=await run('walk',null,60); out.walk={tr:st.querySelectorAll('.ch-tr').length, trA:cs(st.querySelectorAll('.ch-tr')[2]).animationName, trD:cs(st.querySelectorAll('.ch-tr')[2]).animationDelay, mk:cs(st.querySelector('.ch-mk')).animationDelay, dur:cs(st.querySelector('.ch-cv')).animationDuration};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxch').dataset.cycle, on:st.querySelectorAll('.cy-on').length, mkOp:+cs(st.querySelector('.ch-mk')).opacity};
    st=await run('draw',{pos:'',stages:['Um','Dois']},60); out.noMk={mk:st.querySelectorAll('.ch-mk').length, dots:st.querySelectorAll('.ch-dot').length, lbs:[...st.querySelectorAll('.ch-lb')].map(l=>l.className.replace('ch-lb','').trim()).join(',')};
    st=await run('draw',{pos:3},60); out.valley={dn:st.querySelector('.ch-mk').classList.contains('dn')}; st=await run('draw',{pos:4.5},60); out.slope={dn:st.querySelector('.ch-mk').classList.contains('dn')};
    st=await run('draw',{mode:'adkar'},60); const S=[...st.querySelectorAll('.ad-s')]; out.ad={n:S.length, let:[...st.querySelectorAll('.ad-l')].map(l=>l.textContent).join(''), names:[...st.querySelectorAll('.ad-t')].map(l=>l.textContent).join('|'), h:[...st.querySelectorAll('.ad-b')].map(b=>b.style.height).join(','), bar:S.map(s=>s.classList.contains('bar')?1:0).join(''), bp:[...st.querySelectorAll('.ad-bp')].map(b=>b.textContent.trim()).filter(Boolean).join(''), inB:S.map(s=>s.querySelector('.ad-tr').classList.contains('in')?1:0).join(''), scores:[...st.querySelectorAll('.ad-tr em')].map(e=>e.textContent).join(','), barCol:cs(st.querySelector('.ad-s.bar .ad-b')).backgroundColor, b2:cs(st.querySelectorAll('.ad-b')[2]).animationDelay, bA:cs(st.querySelector('.ad-b')).animationName, root:st.querySelector('.fxch.fxad')?1:0, label:AMRT.fxLabel({kind:'change',data:{mode:'adkar'}})+'/'+AMRT.fxLabel({kind:'change',data:{}})};
    st=await run('walk',{mode:'adkar'},60); out.adWalk={ring:cs(st.querySelector('.ad-s.bar .ad-tr')).animationName, d:cs(st.querySelector('.ad-s.bar .ad-tr')).animationDelay};
    st=await run('draw',{mode:'adkar',adkar:[{t:'A',v:5},{t:'B',v:5},{t:'C',v:5},{t:'D',v:5},{t:'E',v:5}]},60); out.adAll={bar:st.querySelectorAll('.ad-s.bar').length, bp:[...st.querySelectorAll('.ad-bp')].map(b=>b.textContent.trim()).filter(Boolean).length};
    st=await run('focus',{mode:'adkar'},2500); out.adFocus={cycle:st.querySelector('.fxad').dataset.cycle, on:st.querySelectorAll('.cy-on').length};
    return out; });
  await p.screenshot({path:SH('08-adkar')}); await p.evaluate(()=>window.__labOff());
  check('S07B-12: curva da mudança: 7 etapas Choque … Integração numa curva de 6 segmentos, rótulos do lado livre (Choque abaixo à direita, Negação acima, Frustração acima à direita, Depressão abaixo, Experimentação / Decisão / Integração acima à esquerda), marcador “Estamos aqui” em 3,4 entre Depressão e Experimentação com a pílula para cima (para baixo cobriria o rótulo “Depressão”), para cima num vale (pos 3) e para baixo numa rampa livre (pos 4,5, rótulos acima), eixos “Moral e desempenho” / “Tempo”; “Curva desenhando” (amDraw 1,6 s; 4º ponto amPopC a 1 s, rótulo a 1,15 s, marcador a 2 s; sem rastro); “Até o estamos aqui” (19 pontos de rastro m8Trail — 3º a 1,64 s —, curva em 1,2 s, marcador a 2,96 s); “Foco percorrendo” (etapa acesa, marcador sempre inteiro); posição vazia esconde o marcador e 2 etapas viram ponta a ponta; ADKAR: 5 etapas A D K A R Consciência … Reforço, barras 80/80/40/60/60 %, a menor (Conhecimento) em laranja como ponto de barreira, notas 4/5…, nota ≥ 4 escrita dentro da barra, barras amGrow (3ª a 0,74 s), rótulo do elemento “ADKAR (curva da mudança)” / “Curva da mudança”; no ADKAR “Até o estamos aqui” pulsa a barreira (m8Ring a 2,1 s); todas em 5 = sem barreira; foco por etapa', ch.n.dots===7&&ch.n.lbs==='ar,up,up ar,-,up al,up al,up al'&&ch.n.txt==='Choque|Negação|Frustração|Depressão|Experimentação|Decisão|Integração'&&ch.n.mk==='Estamos aqui'&&!ch.n.mkDn&&ch.n.tr===0&&ch.n.cv===6&&/Moral e desempenho/.test(ch.n.axes)&&/Tempo/.test(ch.n.axes)&&ch.draw.cv==='amDraw'&&ch.draw.dur==='1.6s'&&ch.draw.d3==='1s'&&ch.draw.l3==='1.15s'&&ch.draw.mk==='2s'&&ch.draw.dotA==='amPopC'&&ch.mkPos&&ch.walk.tr===19&&ch.walk.trA==='m8Trail'&&ch.walk.trD==='1.64s'&&ch.walk.mk==='2.96s'&&ch.walk.dur==='1.2s'&&ch.focus.cycle==='g'&&ch.focus.on===2&&ch.focus.mkOp>.95&&ch.noMk.mk===0&&ch.noMk.dots===2&&ch.noMk.lbs==='ar,up al'&&!ch.valley.dn&&ch.slope.dn&&ch.ad.n===5&&ch.ad.let==='ADKAR'&&ch.ad.names==='Consciência|Desejo|Conhecimento|Habilidade|Reforço'&&ch.ad.h==='80%,80%,40%,60%,60%'&&ch.ad.bar==='00100'&&ch.ad.bp==='ponto de barreira'&&ch.ad.inB==='11000'&&ch.ad.scores==='4/5,4/5,2/5,3/5,3/5'&&ch.ad.barCol==='rgb(247, 140, 22)'&&ch.ad.b2==='0.74s'&&ch.ad.bA==='amGrow'&&ch.ad.root===1&&ch.ad.label==='ADKAR (curva da mudança)/Curva da mudança'&&ch.adWalk.ring==='m8Ring'&&ch.adWalk.d==='2.1s'&&ch.adAll.bar===0&&ch.adAll.bp===0&&ch.adFocus.cycle==='g'&&ch.adFocus.on===1, ch);

  /* ---------- 8. nada cortado nem fora da caixa: 7 modelos × branco/navy (painel) × 100 %/50 %; paleta A&M; textos sem sobreposição ---------- */
  const fitIssues=[], bad=[], ovl=[]; let nFit=0;
  for(const k of KINDS) for(const dark of [false,true]) for(const sc of [1,.5]){
    await lab(p,k,null,dark,sc,null,null); nFit++;
    const iss=await stageCheck(p,'#s7blab .am-stage'); if(iss.length) fitIssues.push(k+(dark?' navy':'')+' '+(sc*100)+'%: '+iss.join('; '));
    if(sc===1){ const o=await overlaps(p,'#s7blab .am-stage'); if(o.length) ovl.push(k+(dark?' navy':'')+': '+o.join('; ')); }
    const pal=await p.evaluate(([k,PAL])=>{ const st=document.querySelector('#s7blab .am-stage'), out=[]; const hex=c=>{ const m=/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)$/.exec(c); if(!m) return c.toUpperCase(); if(m[4]==='0') return 'NONE'; return '#'+[m[1],m[2],m[3]].map(x=>(+x).toString(16).padStart(2,'0')).join('').toUpperCase(); };
      st.querySelectorAll('.fx *').forEach(x=>{ const cs=getComputedStyle(x); [cs.backgroundColor, cs.color].forEach(c=>{ const h=hex(c); if(PAL.indexOf(h)<0) out.push(k+':'+x.className+':'+h); }); if(x instanceof SVGElement&&/^(path|rect|circle|text|line|polygon)$/i.test(x.tagName)){ ['fill','stroke'].forEach(a=>{ const v=x.getAttribute(a); if(v&&PAL.indexOf(v.toUpperCase())<0&&!/^url\(/i.test(v)) out.push(k+':'+a+':'+v); const c=hex(cs[a]); if(c!=='NONE'&&!/^URL\(/.test(c)&&PAL.indexOf(c)<0) out.push(k+':'+a+'~'+c); }); } });
      return out; },[k,PAL]); bad.push(...pal);
    if(sc===1&&!dark) await p.screenshot({path:SH('10-'+k)}); if(sc===1&&dark&&(k==='bmc'||k==='stake')) await p.screenshot({path:SH('11-'+k+'-navy')}); }
  await lab(p,'change',null,false,1,{mode:'adkar'},null); const adIss=await stageCheck(p,'#s7blab .am-stage'); await lab(p,'change',null,true,.5,{mode:'adkar'},null); const adIss2=await stageCheck(p,'#s7blab .am-stage');
  await p.evaluate(()=>window.__labOff());
  check('S07B-13: os 7 modelos (e o ADKAR) no tamanho padrão e a 50 %, em slide branco e em navy com painel branco: nenhum texto cortado, nada fora da caixa nem do slide (stageCheck), nenhum texto editável sobre outro; cores só da paleta A&M (navy, aços, gelos, laranja, branco), nunca vermelho', fitIssues.length===0&&bad.length===0&&ovl.length===0&&nFit===28&&adIss.length===0&&adIss2.length===0, {fitIssues,ovl,adIss,adIss2,bad:[...new Set(bad)].slice(0,20)});

  /* ---------- 9. dados hostis: html() puro nunca escreve NaN/negativo, texto vira texto, atributos não vazam ---------- */
  const hostile=await p.evaluate(()=>{ const out={}, H=(k,d,w,h)=>AMRT.FX[k].html(d,w,h,{variant:AMRT.FX[k].variant,data:d}); const bad=s=>/NaN|Infinity|undefined|(?:width|height|left|top|font-size)\s*:\s*-\d|onmouseover|<img/.test(s);
    const s=H('stake',{items:[{t:'<img src=x>',x:'abc',y:1e9,st:'r" onmouseover="x',tx:-5,ty:'y'},{t:7,x:-50,y:-50,st:{}},null,'texto',{t:'ok',x:50,y:50,st:'apoiador'}],q:'a;b',xlab:{},ylab:null},900,470); out.s={bad:bad(s), esc:/&lt;img src=x&gt;/.test(s), its:(s.match(/class="sk-it"/g)||[]).length, st:(s.match(/sk-d sk-s[a-z]/g)||[]).join(','), cls:!/sk-s[^a-z"]/.test(s)};
    const v=H('valuechain',{support:'<b>x</b>;y',primary:[null,{},'z'],hl:'<1>,2,99,-3',notes:[{n:'2" onmouseover="',x:'<i>'},{n:1e9,x:'x'},'texto'],margin:['m']},0,-10); out.v={bad:bad(v), esc:/&lt;b&gt;x&lt;\/b&gt;/.test(v)&&/&lt;i&gt;/.test(v), s:(v.match(/class="vc-s[ "]/g)||[]).length, p:(v.match(/class="vc-p[ "]/g)||[]).length, hl:(v.match(/ hl"/g)||[]).length, notes:(v.match(/class="vc-nt"/g)||[]).length};
    const b=H('bmc',{kp:'<p>;q',vp:[{},null,'ok'],titles:[1,'<t>'],cs:5},40,40); out.b={bad:bad(b), esc:/&lt;p&gt;/.test(b)&&/&lt;t&gt;/.test(b), blocks:(b.match(/class="bm-b /g)||[]).length, lis:(b.match(/<li /g)||[]).length};
    const j=H('journey',{stages:['<s>',{},null,'B'],emo:'9;-9;x',rows:[{k:'<k>',v:'a|b'},{k:'Dores',v:[null,'<v>']},'linha',null],emolab:'<e>'},1160,470); out.j={bad:bad(j), esc:/&lt;s&gt;/.test(j)&&/&lt;k&gt;/.test(j)&&/&lt;v&gt;/.test(j)&&/&lt;e&gt;/.test(j), h:(j.match(/class="jr-h"/g)||[]).length, c:(j.match(/class="jr-c[ "]/g)||[]).length, dots:(j.match(/class="jr-dot/g)||[]).length, top:(j.match(/jr-dot[^>]*top:([\d.]+)%/g)||[]).map(x=>+/top:([\d.]+)/.exec(x)[1]).every(t=>t>=12&&t<=88)};
    const o=H('okr',{obj:'<o>',krs:[{t:'<t>',v:'abc',tg:-5,u:'<u>',c:'crítico" onmouseover="'},{t:'x',v:1e9,tg:1e-9},null,'texto'],eyebrow:{},owner:['x']},1000,420); out.o={bad:bad(o), esc:/&lt;o&gt;/.test(o)&&/&lt;t&gt;/.test(o)&&/&lt;u&gt;/.test(o), rows:(o.match(/class="ok-r"/g)||[]).length, cls:(o.match(/ok-c c-[a-z]"/g)||[]).join(','), w:(o.match(/width:([\d.]+)%/g)||[]).every(x=>+/[\d.]+/.exec(x)[0]<=100)};
    const c=H('bsc',{persp:'<p>',objs:[{p:'x" onmouseover="',t:'<o>'},{p:-1,t:'a'},{p:1e9,t:'b'},null,'texto'],links:[{a:'x',b:'y'},{a:1,b:3},{a:1,b:1},'texto',null]},1160,470); out.c={bad:bad(c), esc:/&lt;p&gt;/.test(c)&&/&lt;o&gt;/.test(c), bands:(c.match(/class="bs-bd/g)||[]).length, cards:(c.match(/class="bs-c /g)||[]).length, links:(c.match(/class="bs-a"/g)||[]).length};
    const m=H('change',{stages:[null,'<x>',{}],pos:'99',marker:'<m>',mode:'<img>'},1100,420); out.m={bad:bad(m), esc:/&lt;x&gt;/.test(m)&&/&lt;m&gt;/.test(m), dots:(m.match(/class="ch-dot"/g)||[]).length, mk:(m.match(/class="ch-mk/g)||[]).length, curve:/class="ch-cv"/.test(m)};
    const a=H('change',{mode:'adkar',adkar:[{t:'<a>',v:'9'},{v:-3},null,'texto',{t:'e',v:'2,5'},{t:'sobra',v:1}]},40,40); out.a={bad:bad(a), esc:/&lt;a&gt;/.test(a), steps:(a.match(/class="ad-s/g)||[]).length, h:(a.match(/height:([\d.]+)%/g)||[]).join(','), names:/Desejo/.test(a)&&/Conhecimento/.test(a)&&!/sobra/.test(a)};
    return out; });
  check('S07B-14: html() puro com dados hostis (tags, objetos, nulos, NaN, negativos, 1e9, caixa 40×40 / 0×−10): nunca escreve NaN/Infinity/undefined nem tamanho negativo, escapa todo texto, posturas e confianças viram uma letra válida (nada de atributo injetado), itens inválidos somem ou viram vazios sem quebrar a contagem, clamps em posições, emoção, notas, perspectivas e notas ADKAR (nome padrão quando falta, no máximo 5 etapas)', !Object.keys(hostile).some(k=>hostile[k].bad)&&hostile.s.esc&&hostile.s.its===3&&hostile.s.st==='sk-d sk-sr,sk-d sk-sn,sk-d sk-sa,sk-d sk-sa,sk-d sk-sn,sk-d sk-sr'&&hostile.s.cls&&hostile.v.esc&&hostile.v.s===2&&hostile.v.p===3&&hostile.v.hl===2&&hostile.v.notes===1&&hostile.b.esc&&hostile.b.blocks===9&&hostile.b.lis===3&&hostile.j.esc&&hostile.j.h===4&&hostile.j.c===16&&hostile.j.dots===4&&hostile.j.top&&hostile.o.esc&&hostile.o.rows===4&&hostile.o.cls==='ok-c c-c",ok-c c-n",ok-c c-n",ok-c c-n"'&&hostile.o.w&&hostile.c.esc&&hostile.c.bands===2&&hostile.c.cards===3&&hostile.c.links===1&&hostile.m.esc&&hostile.m.dots===3&&hostile.m.mk===1&&hostile.m.curve&&hostile.a.esc&&hostile.a.steps===5&&hostile.a.h==='height:100%,height:0%,height:0%,height:0%,height:60%'&&hostile.a.names, hostile);

  /* ---------- 10. vitrine, slide navy (painel branco), apresentação + Ampliar com o nome do preset ---------- */
  const gal=await p.evaluate((KINDS)=>{ const it=AMStudio.gallery.items(), fam={}; it.forEach(i=>fam[i.fam]=(fam[i.fam]||0)+1); const ids=it.filter(i=>i.fam==='model').map(i=>i.id); return {ok:KINDS.every(k=>AMRT.FX[k].variants.every(v=>ids.indexOf('model:'+k+':'+v[0])>=0)), n:fam.model, sum:Object.keys(AMRT.FX).filter(k=>AMRT.FX[k].model).reduce((a,k)=>a+AMRT.FX[k].variants.length,0), noPreset:!it.some(i=>/ansoff|sipoc|preset/i.test(i.id+i.name)), cats:it.filter(i=>/^model:(okr|journey)/.test(i.id)).map(i=>i.cat).join(',')}; },KINDS);
  check('S07B-15: a vitrine de efeitos lista cada efeito dos 7 modelos (model:kind:efeito, com a categoria do modelo), sem cards de preset, e o total da família “Modelos” continua igual à soma dos efeitos de todos os modelos (S01-05)', gal.ok&&gal.n===gal.sum&&gal.noPreset&&gal.cats==='Evolução,Evolução,Evolução,Evolução,Indicadores,Indicadores,Indicadores', gal);
  await fresh(p); await p.evaluate(()=>{ AMStudio.addSlide('blank-dark'); AMStudio.insertFx('bsc'); AMStudio.insertFx('okr',null,{x:640,y:360}); }); await sleep(400);
  const dk=await p.evaluate(()=>{ const e=AMStudio.deck.slides[1].els, st=document.querySelector('#wrap .am-stage'); return {panel:e.map(x=>x.data.panel).join(','), pins:st.querySelectorAll('.fx-panel .fx-pin > .fx').length}; });
  await p.evaluate(()=>{ const e=AMStudio.deck.slides[1].els; e[0].x=20; e[0].y=20; e[0].w=720; e[0].h=330; e[1].x=760; e[1].y=380; e[1].w=500; e[1].h=320; AMStudio.renderAll(); AMStudio.commit(); }); await sleep(400);
  const dkIss=await stageCheck(p,'#wrap .am-stage'); await sleep(2600); await p.screenshot({path:SH('12-navy-painel')});
  check('S07B-16: em slide navy os modelos entram no painel branco (.fx-panel > .fx-pin) e, redimensionados (720×330 e 500×320), continuam sem nada cortado nem fora da caixa', dk.panel==='white,white'&&dk.pins===2&&dkIss.length===0, {dk,dkIss});
  await fresh(p); await p.evaluate(()=>{ AMStudio.addSlide('blank-light'); const P=AMRT.PRESETS.ansoff; AMStudio.insertFx('matrix',null,{x:300,y:190},P.variant,Object.assign(JSON.parse(JSON.stringify(P.data)),{preset:'ansoff'})); AMStudio.insertFx('stake',null,{x:960,y:190},'drop'); AMStudio.insertFx('change',null,{x:640,y:560},'draw'); const e=AMStudio.deck.slides[1].els; e[0].w=560; e[0].h=300; e[0].x=30; e[0].y=30; e[1].w=600; e[1].h=300; e[1].x=650; e[1].y=30; e[2].w=1180; e[2].h=340; e[2].x=50; e[2].y=360; AMStudio.renderAll(); AMStudio.commit(); AMStudio.goSlide(1); }); await sleep(300);
  await p.keyboard.press('F5'); await sleep(900); await p.keyboard.press('ArrowRight'); await sleep(3200);
  const pres=await p.evaluate(()=>{ const on=document.querySelector('#presenter .amp-slide.on'); return {open:document.getElementById('presenter').classList.contains('open'), pos:document.querySelector('#presenter .amp-pos').textContent.trim(), fx:['.fxmx','.fxsk','.fxch'].map(s=>on.querySelectorAll(s).length).join(''), visible:[...on.querySelectorAll('.mx-it,.sk-it,.ch-dot')].every(x=>+getComputedStyle(x).opacity>.95), zoomables:AMRT.zoomables(AMStudio.deck.slides[1]).map(e=>e.kind).join(',')}; });
  await p.screenshot({path:SH('13-apresentacao')});
  await p.keyboard.press('z'); await sleep(600);
  const zm=await p.evaluate(()=>{ const z=document.querySelector('#presenter .amp-zm'); return {open:!!z, fx:z?z.querySelectorAll('.fxch').length:0, foot:z?z.textContent:''}; });
  await p.keyboard.press('Escape'); await sleep(300); await p.keyboard.press('Escape'); await sleep(400);
  await p.evaluate(()=>{ AMStudio.deck.slides[1].els[2].zoom=false; AMStudio.deck.slides[1].els[1].zoom=false; AMStudio.commit(); }); await p.keyboard.press('F5'); await sleep(900); await p.keyboard.press('ArrowRight'); await sleep(1200); await p.keyboard.press('z'); await sleep(600);
  const zm2=await p.evaluate(()=>{ const z=document.querySelector('#presenter .amp-zm'); return {open:!!z, foot:z?z.textContent:'', zoomables:AMRT.zoomables(AMStudio.deck.slides[1]).map(e=>e.kind).join(',')}; });
  await p.keyboard.press('Escape'); await sleep(300); await p.keyboard.press('Escape'); await sleep(400);
  check('S07B-17: na apresentação (F5 → slide 2) a matriz de Ansoff, o mapa de stakeholders e a curva entram inteiros e são ampliáveis (a maior primeiro: curva); Z abre o ampliado com a curva re-renderizada e o rodapé “Curva da mudança”; numa nova apresentação com a curva e o mapa sem ampliar (zoom = false), Z amplia a matriz com o rodapé “Matriz de Ansoff” (nome do preset); Esc fecha o ampliado e depois sai da apresentação', pres.open&&/^02/.test(pres.pos)&&pres.fx==='111'&&pres.visible&&pres.zoomables==='change,stake,matrix'&&zm.open&&zm.fx===1&&/Curva da mudança/.test(zm.foot)&&zm2.open&&zm2.zoomables==='matrix'&&/Matriz de Ansoff/.test(zm2.foot)&&!/Curva da mudança/.test(zm2.foot)&&await p.evaluate(()=>!document.getElementById('presenter').classList.contains('open')), {pres,zm,zm2});

  /* ---------- 11. saneamento ao abrir (safeEl + norm), export autônomo e reabertura ---------- */
  await fresh(p); for(const k of KINDS) await p.evaluate(k=>AMStudio.insertFx(k),k); await sleep(300);
  const d0=await p.evaluate(()=>JSON.parse(JSON.stringify(AMStudio.deck)));
  const mk=(id,kind,data,v)=>({id,type:'fx',kind,x:10,y:10,w:600,h:300,variant:v,data});
  d0.slides[0].els.push(mk('tSk','stake',{items:'CEO | 60 | 90 | a\nTI | 30 | 20 | r | 70 | 40',q:'A;B;C;D',panel:'white'},'move'), mk('tJr','journey',{stages:'A;B',emo:'1;-1',rows:'Ações | faz | compra\nDores | x | y'},'nope'), mk('tBs','bsc',{persp:'F\nC',objs:'1 | Um\n2 | Dois',links:'2 | 1'}), mk('tOk','okr',{krs:'KR um | 5 | 10 | % | ok'}), mk('tVc','valuechain',{support:'a;b',primary:'c;d',notes:'2 | nota'}), mk('tBm','bmc',{kp:'a;b',titles:'T1'}), mk('tCh','change',{adkar:'A | 5\nB | 1',stages:'x;y;z',mode:'adkar'}), mk('tPr','matrix',{preset:'ansoff',items:[{t:'a',x:10,y:10}]}), mk('tBad','matrix',{preset:'<img src=x>'}), mk('tNo','journey',{},undefined), {id:'tStr',type:'fx',kind:'okr',x:10,y:10,w:600,h:300,data:'texto'});
  await p.evaluate(d=>AMStudio.loadDeck(d,null,true,true), d0); await sleep(500);
  const ld=await p.evaluate(()=>{ const e=AMStudio.deck.slides[0].els, f=id=>e.filter(x=>x.id===id)[0]; return {n:e.length, sk:JSON.stringify(f('tSk').data.items)+'|'+f('tSk').data.q.join('')+'|'+f('tSk').variant+'|'+f('tSk').data.panel, jr:JSON.stringify(f('tJr').data.rows)+'|'+f('tJr').data.stages.join('')+'|'+f('tJr').data.emo.join(',')+'|'+(f('tJr').variant||'-'), bs:JSON.stringify(f('tBs').data.objs)+'|'+JSON.stringify(f('tBs').data.links)+'|'+f('tBs').data.persp.join(''), ok:JSON.stringify(f('tOk').data.krs), vc:JSON.stringify(f('tVc').data.notes)+'|'+f('tVc').data.support.join('')+'|'+f('tVc').data.primary.join(''), bm:f('tBm').data.kp.join('')+'|'+f('tBm').data.titles.join(''), ch:JSON.stringify(f('tCh').data.adkar)+'|'+f('tCh').data.stages.join('')+'|'+f('tCh').data.mode, pr:AMRT.fxLabel(f('tPr'))+'|'+f('tPr').data.preset, bad:AMRT.fxLabel(f('tBad'))+'|'+(f('tBad').data.preset||'-'), no:Object.keys(f('tNo').data).length, str:f('tStr').data.krs.length, st:document.querySelectorAll('#wrap .am-stage .am-el .am-fxw > .fx').length}; });
  check('S07B-18: ao abrir um arquivo editado à mão, safeEl + norm saneiam: listas em texto (“A;B”, “x;y;z”, “a\\nb”) viram arrays, linhas em texto (“CEO | 60 | 90 | a”, “Ações | faz | compra”, “1 | Um”, “2 | 1”, “KR um | 5 | 10 | % | ok”, “2 | nota”, “A | 5”) viram objetos (strings ficam strings, a jornada guarda as células em v[]), efeito inválido cai, painel e modo ficam, data.preset válido dá o nome “Matriz de Ansoff” e um preset inválido fica como texto inerte com o nome do motor, data em texto volta ao padrão do modelo e data vazio fica vazio (renderiza sem itens); os 18 elementos renderizam', ld.n===18&&ld.sk==='[{"t":"CEO","x":"60","y":"90","st":"a","tx":"","ty":""},{"t":"TI","x":"30","y":"20","st":"r","tx":"70","ty":"40"}]|ABCD|move|white'&&ld.jr==='[{"k":"Ações","v":["faz","compra"]},{"k":"Dores","v":["x","y"]}]|AB|1,-1|-'&&ld.bs==='[{"p":"1","t":"Um"},{"p":"2","t":"Dois"}]|[{"a":"2","b":"1"}]|FC'&&ld.ok==='[{"t":"KR um","v":"5","tg":"10","u":"%","c":"ok"}]'&&ld.vc==='[{"n":"2","x":"nota"}]|ab|cd'&&ld.bm==='ab|T1'&&ld.ch==='[{"t":"A","v":"5"},{"t":"B","v":"1"}]|xyz|adkar'&&ld.pr==='Matriz de Ansoff|ansoff'&&ld.bad==='Matriz de priorização (2×2)|<img src=x>'&&ld.no===0&&ld.str===4&&ld.st===18, ld);
  const html=await p.evaluate(()=>AMStudio.exportHTML()); const f=path.join(TMP,'saved-s07b.html'); fs.writeFileSync(f,html);
  const dj=deckJSON(html); const q=await page(ctx,'file://'+f,'exp',1500);
  const ex=await q.evaluate((KINDS)=>{ const sl=document.querySelectorAll('.amp .amp-slide'); return {slides:sl.length, rt:typeof AMRT!=='undefined'&&KINDS.every(k=>!!AMRT.FX[k])&&typeof AMRT.PRESETS==='object'&&typeof AMRT.FX.matrix.label==='function', ed:typeof AMStudio==='undefined'&&typeof AMCover==='undefined', fx:KINDS.map(k=>sl[0].querySelectorAll('.am-k-'+k+' .am-fxw > .fx').length).join(''), css:[...document.styleSheets].some(s=>{ try{ return [...s.cssRules].some(r=>/\.fxsk/.test(r.selectorText||'')); }catch(e){ return false; } }), kf:[...document.styleSheets].some(s=>{ try{ return [...s.cssRules].some(r=>r.name==='m8Flow'); }catch(e){ return false; } })}; },KINDS);
  await sleep(2500); await q.screenshot({path:SH('14-exportado')});
  check('S07B-19: o arquivo exportado é autônomo (runtime + rt-models3 com AMRT.PRESETS e o gancho label, sem editor/capa), guarda o deck em #am-deck-data com os 18 elementos (dados já normalizados, só {k, v} nas linhas da jornada — html() não escreve nos dados —, data.preset mantido), renderiza os 7 tipos no player com o CSS e os keyframes m8', ex.slides===1&&ex.rt&&ex.ed&&ex.fx==='2223322'&&ex.css&&ex.kf&&dj&&dj.slides[0].els.length===18&&dj.slides[0].els.filter(e=>e.id==='tPr')[0].data.preset==='ansoff'&&dj.slides[0].els.filter(e=>e.kind==='journey').every(e=>!e.data.rows||(Array.isArray(e.data.rows)&&e.data.rows.every(r=>Array.isArray(r.v)&&Object.keys(r).sort().join()==='k,v'))), {ex,n:dj&&dj.slides[0].els.length});
  check('S07B-20: export sem onerror/onmouseover/onclick (CR-04) e sem “</script” fora das tags', !/onerror|onmouseover|onclick/i.test(html)&&(html.match(/<\/script/g)||[]).length===(html.match(/<script[\s>]/g)||[]).length, {s:(html.match(/<script[\s>]/g)||[]).length,e:(html.match(/<\/script/g)||[]).length});
  await q.close();
  const r=await page(ctx, FILE+'?nocover', 'reopen');
  await r.evaluate(h=>AMStudio.openFile(new File([h],'saved-s07b.html',{type:'text/html'})), html); await sleep(1500);
  const ro=await r.evaluate((KINDS)=>{ const e=AMStudio.deck.slides[0].els; return {n:e.length, kinds:e.slice(0,7).map(x=>x.kind).join(','), v:e.slice(0,7).map(x=>x.variant||'-').join(','), stake:e.filter(x=>x.kind==='stake').map(x=>x.data.items.length).join('|'), pr:AMRT.fxLabel(e.filter(x=>x.id==='tPr')[0]), st:KINDS.every(k=>document.querySelector('#wrap .am-stage .am-k-'+k+' .fx'))}; },KINDS);
  check('S07B-21: reabrir o arquivo exportado no editor devolve os 18 elementos com dados e efeitos (stakeholders 7 e 2 itens; a matriz de Ansoff com o nome do preset) e todos renderizam', ro.n===18&&ro.kinds===KINDS.join(',')&&ro.v==='drop,build,blocks,walk,cascade,bottomup,draw'&&ro.stake==='7|2'&&ro.pr==='Matriz de Ansoff'&&ro.st, ro);
  await r.close();

  /* ---------- 12. edição no slide: stakeholder, célula da jornada; painel acompanha ---------- */
  await fresh(p); await p.evaluate(()=>AMStudio.insertFx('stake')); await sleep(300);
  const lsp=await p.$('#wrap .am-stage [data-e="items.3.t"]'); const lb=await lsp.boundingBox(); await p.mouse.dblclick(lb.x+lb.width/2, lb.y+lb.height/2); await sleep(200);
  const ce=await p.evaluate(()=>{ const a=document.activeElement; return {ce:a&&a.isContentEditable, path:a&&a.dataset.e, txt:a&&a.textContent}; });
  await p.keyboard.type('Sindicato local'); await p.keyboard.press('Enter'); await sleep(300);
  const ie=await p.evaluate(()=>({t:AMStudio.deck.slides[0].els[0].data.items[3].t, st:AMStudio.deck.slides[0].els[0].data.items[3].st, shown:document.querySelector('#wrap .am-stage [data-e="items.3.t"]').textContent, ta:document.querySelector('#props textarea[data-codec="rows:t|x:n|y:n|st|tx:n|ty:n"]').value.split('\n')[3], editing:!!document.querySelector('#wrap .am-stage [contenteditable]')}));
  await fresh(p); await p.evaluate(()=>AMStudio.insertFx('journey')); await sleep(300);
  const csp=await p.$('#wrap .am-stage [data-e="rows.2.v.1"]'); const cb=await csp.boundingBox(); await p.mouse.dblclick(cb.x+cb.width/2, cb.y+cb.height/2); await sleep(200);
  const ce2=await p.evaluate(()=>{ const a=document.activeElement; return {ce:a&&a.isContentEditable, path:a&&a.dataset.e}; });
  await p.keyboard.type('Planos pouco claros'); await p.keyboard.press('Enter'); await sleep(300);
  const ie2=await p.evaluate(()=>({v:AMStudio.deck.slides[0].els[0].data.rows[2].v[1], shown:document.querySelector('#wrap .am-stage [data-e="rows.2.v.1"]').textContent, ta:document.querySelector('#props textarea[data-codec="rows:k|*v"]').value.split('\n')[2]}));
  await p.fill('#props textarea[data-codec="rows:k|*v"]','Ações | a | b | c | d | e | f\nDores | 1 | 2 | 3 | 4 | 5 | 6'); await sleep(300);
  const ie3=await p.evaluate(()=>({rows:AMStudio.deck.slides[0].els[0].data.rows.length, v:AMStudio.deck.slides[0].els[0].data.rows[1].v.join(''), cells:document.querySelectorAll('#wrap .am-stage .jr-c').length, pain:document.querySelectorAll('#wrap .am-stage .jr-pain').length}));
  await p.screenshot({path:SH('15-edicao-jornada')});
  check('S07B-22: duplo clique no nome de um stakeholder edita no slide (contenteditable em items.3.t); Enter grava “Sindicato local” mantendo a postura, redesenha e o painel acompanha a linha; duplo clique numa célula da jornada edita rows.2.v.1 e grava no array da linha; o painel “Linhas (nome | células)” reescreve as linhas (2 linhas × 6 células, “Dores” com marcadores)', ce.ce&&ce.path==='items.3.t'&&ce.txt==='Sindicato'&&ie.t==='Sindicato local'&&ie.st==='r'&&ie.shown==='Sindicato local'&&/^Sindicato local \| 60 \| 38 \| r/.test(ie.ta)&&!ie.editing&&ce2.ce&&ce2.path==='rows.2.v.1'&&ie2.v==='Planos pouco claros'&&ie2.shown==='Planos pouco claros'&&/^Dores \| Informação dispersa \| Planos pouco claros/.test(ie2.ta)&&ie3.rows===2&&ie3.v==='123456'&&ie3.cells===12&&ie3.pain===6, {ce,ie,ce2,ie2,ie3});

  /* ---------- 13. barra de ferramentas sem estouro (nenhum botão novo) ---------- */
  await p.setViewportSize({width:1280,height:720}); await sleep(400);
  const ov=await p.evaluate(()=>{const t=document.getElementById('top'), rb=document.getElementById('rib'), s=document.getElementById('bSave').getBoundingClientRect(); return {top:t.scrollWidth<=t.clientWidth, rib:rb.scrollWidth<=rb.clientWidth, save:s.right<=innerWidth}; });
  await p.click('#bModels'); await sleep(700); const dw=await p.evaluate(()=>{ const d=document.getElementById('dSearch'); return {chips:document.querySelectorAll('#mCats .chip').length, fits:d.scrollWidth<=d.clientWidth+1, h:d.getBoundingClientRect().height}; }); await p.screenshot({path:SH('16-gaveta-1280')}); await p.click('#bFxClose'); await sleep(200);
  check('S07B-23: barra de ferramentas e topo sem estouro em 1280 (os modelos e presets vivem na Biblioteca de modelos; nenhum botão novo); os chips de categoria cabem na largura da gaveta', ov.top&&ov.rib&&ov.save&&dw.chips>=9&&dw.fits&&dw.h<140, {ov,dw});

  check('Zero erros de console', errs.length===0, errs);
  console.log(results.join('\n'));
  console.log(failed?('FALHAS: '+failed):'TUDO OK', JSON.stringify({errs}));
  await b.close(); try{ fs.rmSync(TMP,{recursive:true,force:true}); }catch(e){}
  process.exit(failed?1:0);
})().catch(e=>{ console.log(results.join('\n')); console.error('ERRO', e); process.exit(2); });
