/* test-s07: Modelos de consultoria A (item 5). rt-models2.js/.css: sete modelos novos na Biblioteca de modelos — ciclo PDCA
   (Processos), cronograma Gantt com linha do “hoje” e caminho crítico, AS-IS → TO-BE e roadmap em ondas / horizontes (Evolução),
   5 Forças de Porter, árvore de problemas (MECE, codec outline:3 com “ = valor” e “[*]”) e matriz BCG (Estratégia) — cada um com 3–4
   efeitos (seletor “Efeito ▾”), edição no slide por duplo clique ([data-e]), campos no painel (lines / rows / outline), palavras-chave
   de busca, categorias certas na gaveta, posições do Gantt por rótulo (“Mar”, “S5”, “dd/mm”), saneamento de dados hostis, painel
   branco em slide navy, nada cortado nem fora da caixa (stageCheck, a ideia do slideCheck do test-cover) em branco/navy e 100 %/50 %,
   paleta A&M (nunca vermelho), vitrine, apresentação + Ampliar, export autônomo (CR-04) e reabertura.
   Uso: python3 assemble.py && node test-s07.js (o qa-gate.sh pega qualquer test-s[0-9][0-9]*.js) */
process.env.NODE_PATH='/opt/node22/lib/node_modules'; require('module').Module._initPaths();
const {chromium}=require('playwright'); const path=require('path'); const fs=require('fs'); const os=require('os');
const FILE='file://'+path.join(__dirname,'AM-Studio-Editor.html');
const FONTS=process.env.AM_FONTS_DIR||path.join(__dirname,'..','fonts2');
const SHOTS=path.join(__dirname,'shots'); fs.mkdirSync(SHOTS,{recursive:true});
const SH=f=>path.join(SHOTS,'s07-'+f+'.png');
const TMP=fs.mkdtempSync(path.join(os.tmpdir(),'canteiro-s07-'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const results=[]; let failed=0; const errs=[];
function check(name, ok, info){ results.push((ok?'PASS ':'FAIL ')+name+(info!==undefined&&!ok?'  '+JSON.stringify(info):'')); if(!ok) failed++; }
async function fonts(p){ if(!fs.existsSync(path.join(FONTS,'gf.css'))) return;
  await p.route('https://fonts.googleapis.com/**',r=>r.fulfill({status:200,contentType:'text/css',body:fs.readFileSync(path.join(FONTS,'gf.css'),'utf8')}));
  await p.route('https://fonts.gstatic.com/**',r=>{const f=path.join(FONTS,path.basename(new URL(r.request().url()).pathname)); return fs.existsSync(f)?r.fulfill({status:200,contentType:'font/woff2',body:fs.readFileSync(f)}):r.abort();}); }
async function page(ctx, url, tag, wait){ const p=await ctx.newPage(); await fonts(p);
  p.on('pageerror',e=>errs.push(tag+' pageerror: '+e.message));
  p.on('console',m=>{ if(m.type()==='error'&&!/net::|Failed to load/.test(m.text())) errs.push(tag+': '+m.text()); });
  if(url) await p.goto(url); await sleep(wait||800); return p; }
const els=p=>p.evaluate(()=>AMStudio.deck.slides[AMStudio.cur].els.map(e=>JSON.parse(JSON.stringify(e))));
const last=async p=>{ const e=await els(p); return e[e.length-1]; };
const fresh=p=>p.evaluate(()=>{ AMStudio.closeMenus(); AMStudio.loadDeck(AMStudio.newDeck(),null,true,true); });
const deckJSON=html=>{ const m=html.match(/<script type="application\/json" id="am-deck-data">([\s\S]*?)<\/script>/); return m?JSON.parse(m[1]):null; };
const KINDS=['pdca','gantt','asistobe','porter','roadmap','issuetree','bcg'];
const CAT={pdca:'Processos',gantt:'Evolução',asistobe:'Evolução',porter:'Estratégia',roadmap:'Evolução',issuetree:'Estratégia',bcg:'Estratégia'};
const ROOT={pdca:'.fxpd',gantt:'.fxgt',asistobe:'.fxab',porter:'.fxpt',roadmap:'.fxrm',issuetree:'.fxit',bcg:'.fxbc'};
/* paleta A&M + cinzas/gelos já usados pelo runtime (matriz, grade) + branco/transparente: toda cor dos modelos tem de estar aqui (nunca vermelho) */
const PAL=['#002A46','#4A6FA5','#A3B8D6','#F78C16','#C9D6E8','#13406A','#43698F','#7EA1C3','#DCE5F0','#EEF2F7','#E3EAF2','#F3F6FA','#EEF0F3','#E2E7EF','#566579','#3E4C5E','#FFFFFF','#FFF','NONE','TRANSPARENT','CURRENTCOLOR'];
/* bancada: palco 1280×720 em escala 1:1 por cima do editor (a mesma do test-s05/s06) */
const LAB=`window.__lab=function(slide,play){ var d=document.getElementById('s7lab'); if(!d){ d=document.createElement('div'); d.id='s7lab'; d.style.cssText='position:fixed;left:0;top:0;width:1280px;height:720px;z-index:99999;background:#fff'; document.body.appendChild(d); }
  d.innerHTML=''; d.style.display='block'; var st=AMRT.renderSlide(slide,{play:!!play}); d.appendChild(st); if(play){ st.classList.remove('am-pre'); void st.offsetWidth; st.classList.add('am-in'); if(d._c) d._c(); d._c=AMRT.runFx(st); } return st; };
  window.__labOff=function(){ var d=document.getElementById('s7lab'); if(d){ if(d._c) d._c(); d.innerHTML=''; d.style.display='none'; } };
  window.__el=function(k,v,dark,sc,data){ var F=AMRT.FX[k], w=F.w*(sc||1), h=F.h*(sc||1), d=data||JSON.parse(JSON.stringify(F.data)); if(dark) d.panel='white'; return {id:'m',type:'fx',kind:k,variant:v||F.variant,x:(1280-w)/2,y:(720-h)/2,w:w,h:h,data:d,anim:{in:'none'}}; };`;
/* o mesmo detector de sobreposição/transbordamento do test-cover (slideCheck), num palco qualquer: texto e peças fora da caixa ou do slide, texto cortado */
async function stageCheck(p, sel){
  return p.evaluate((sel)=>{
    const st=document.querySelector(sel), sr=st.getBoundingClientRect(), k=1280/sr.width, issues=[], boxes=[];
    const L=r=>({x:(r.left-sr.left)*k,y:(r.top-sr.top)*k,r:(r.right-sr.left)*k,b:(r.bottom-sr.top)*k});
    st.querySelectorAll('.am-el[data-id]').forEach(n=>{
      let u=null; const add=r=>{ if(r.width<1||r.height<1) return; const q=L(r); u=u?{x:Math.min(u.x,q.x),y:Math.min(u.y,q.y),r:Math.max(u.r,q.r),b:Math.max(u.b,q.b)}:q; };
      const walker=document.createTreeWalker(n,NodeFilter.SHOW_TEXT); let t; while((t=walker.nextNode())){ if(!t.textContent.trim()) continue; const rg=document.createRange(); rg.selectNodeContents(t); [...rg.getClientRects()].forEach(add); }
      n.querySelectorAll('svg rect,svg circle,svg path,svg line,img,.pd-l,.gt-b,.gt-ms,.ab-a,.ab-b,.pt-f,.pt-c,.rm-ch,.rm-ms,.it-n,.bc-b,.bc-q').forEach(e=>add(e.getBoundingClientRect()));
      n.querySelectorAll('.pd-l,.pd-c,.gt-t,.ab-a,.ab-b,.ab-t,.pt-f,.pt-c,.rm-ch,.rm-ln b,.it-n,.rm-hd span,.gt-ps span,.bc-q').forEach(x=>{ if(x.scrollHeight>x.clientHeight+1||x.scrollWidth>x.clientWidth+1) issues.push('corte em "'+x.textContent.slice(0,24)+'"'); });
      if(!u) return; const nb=L(n.getBoundingClientRect());
      if(u.x<-1||u.y<-1||u.r>1281||u.b>721) issues.push('fora do slide '+JSON.stringify([u.x,u.y,u.r,u.b].map(Math.round)));
      if(u.x<nb.x-14||u.y<nb.y-14||u.r>nb.r+14||u.b>nb.b+14) issues.push('fora da caixa '+JSON.stringify([u.x-nb.x,u.y-nb.y,u.r-nb.r,u.b-nb.b].map(Math.round)));
      boxes.push({id:n.dataset.id,u});
    });
    for(let i=0;i<boxes.length;i++) for(let j=i+1;j<boxes.length;j++){ const a=boxes[i].u,b=boxes[j].u; const w=Math.min(a.r,b.r)-Math.max(a.x,b.x), h=Math.min(a.b,b.b)-Math.max(a.y,b.y); if(w>2&&h>2) issues.push('sobreposição '+boxes[i].id+'×'+boxes[j].id); }
    return issues;
  }, sel);
}
const anim=(p,sel,i)=>p.evaluate(([sel,i])=>{ const n=document.querySelectorAll('#s7lab '+sel)[i||0]; if(!n) return null; const cs=getComputedStyle(n); return {name:cs.animationName, delay:cs.animationDelay}; },[sel,i||0]);
async function lab(p,k,v,dark,sc,data,wait){ await p.evaluate(([k,v,dark,sc,data,play])=>{ window.__lab({bg:dark?'#002A46':'#fff',els:[window.__el(k,v,dark,sc,data)]}, play); },[k,v||null,!!dark,sc||1,data||null,wait!=null]); await sleep(wait||60); }
(async()=>{
  const b=await chromium.launch();
  const ctx=await b.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
  const p=await page(ctx, FILE+'?nocover', 'ed');
  await p.evaluate(LAB);

  /* ---------- 1. registro, resolvedor de posições do Gantt e codec da árvore ---------- */
  const reg=await p.evaluate((KINDS)=>KINDS.map(k=>{ const F=AMRT.FX[k]; if(!F) return {k,missing:true}; return {k,model:!!F.model,cat:F.cat,nv:(F.variants||[]).length,labels:(F.variants||[]).every(v=>v[0]&&v[1]&&v[2]&&/^[a-z]+$/.test(v[0])),defOk:(F.variants||[]).some(v=>v[0]===F.variant),size:[F.w,F.h],nf:(F.fields||[]).length,tip:!!F.tip,kw:!!F.kw&&F.kw.length>20,html:typeof F.html==='function',name:F.name}; }),KINDS);
  const fx=await p.evaluate(()=>({fns:['ganttPos','treeParse','treeText'].every(k=>typeof AMRT[k]==='function'), it:typeof AMRT.FX.issuetree.norm==='function'&&typeof AMRT.FX.issuetree.outlineParse==='function'&&typeof AMRT.FX.issuetree.outlineText==='function', itField:AMRT.FX.issuetree.fields[0][2], gtField:AMRT.FX.gantt.fields.map(f=>f[2]||'text').join('|'), bcField:AMRT.FX.bcg.fields[0][2], rmField:AMRT.FX.roadmap.fields[2][2]}));
  check('S07-01: os 7 modelos registrados (model:true) nas categorias certas (Processos / Evolução / Estratégia), cada um com 3–4 efeitos com chave, rótulo e descrição, efeito padrão válido, tamanho ≤ 1172×470, campos, dica e palavras-chave; AMRT.ganttPos/treeParse/treeText e os ganchos norm/outlineParse/outlineText da árvore; codecs: árvore outline:3, Gantt lines|rows|texto, BCG e roadmap rows', reg.every(r=>!r.missing&&r.model&&r.cat===CAT[r.k]&&r.nv>=3&&r.nv<=4&&r.labels&&r.defOk&&r.size[0]<=1172&&r.size[1]<=470&&r.nf>=1&&r.tip&&r.kw&&r.html)&&fx.fns&&fx.it&&fx.itField==='outline:3'&&fx.gtField==='lines|rows:t|s|e|k|text'&&fx.bcField==='rows:t|x:n|y:n|s:n|tx:n|ty:n'&&fx.rmField==='rows:t|l:n|s:n|e:n|k', {reg,fx});
  const gp=await p.evaluate(()=>{ const P=['Jan','Fev','Mar','Abr','Mai','Jun'], g=AMRT.ganttPos; const S=['S1','S2','S3','S4']; return {n:g('1,5',P), n2:g(2,P), lab:g('mar',P), labE:g('Mar',P,true), s5:g('S5',P), s3:g('s3',S,true), sem:g('semana 2',S), ddmm:+g('15/03',P).toFixed(3), ddmmyy:g('01/04/2026',P), mes:g('março',P), mesAno:g('jan/26',['jan/26','fev/26']), mesAnoNo:g('jan/27',['jan/26','fev/26']), bad:g('xyz',P), empty:g('',P), nul:g(null,P)}; });
  check('S07-02: AMRT.ganttPos: número com vírgula (1,5) ou ponto, rótulo do período (fim = +1), “S5”/“s3”/“semana 2”, “dd/mm” (15/03 = 2,452), “dd/mm/aaaa”, “março”, “jan/26” pelos rótulos; desconhecido, vazio e nulo = null', gp.n===1.5&&gp.n2===2&&gp.lab===2&&gp.labE===3&&gp.s5===4&&gp.s3===3&&gp.sem===1&&gp.ddmm===2.452&&gp.ddmmyy===3&&gp.mes===2&&gp.mesAno===0&&gp.mesAnoNo===null&&gp.bad===null&&gp.empty===null&&gp.nul===null, gp);
  const tc=await p.evaluate(()=>{ const P=AMRT.treeParse, T=AMRT.treeText;
    const a=P('Pergunta = 100 [*]\n  Hipótese A [*]\n\tHipótese B\n      Pulo (vira 2)\n        Nível 3\n          Nível 4 (vira 3)\n- Marcador\n\nSem valor = \nReceita = R$ 12 M');
    const arr=P([{t:' Um ',lv:0,v:'5',hl:1},null,{t:'',lv:1},{t:'Dois',lv:'9',hl:'1'},'Três = 7 [*]',{t:{},lv:0},{t:'x'.repeat(300),lv:0,v:'y'.repeat(80)}]);
    return {items:a.map(o=>o.lv+':'+o.t+(o.v?'='+o.v:'')+(o.hl?'*':'')), rt:T(a)===T(P(T(a))), txt:T(a).split('\n')[4], idx:arr.map(o=>(o.i==null?'-':o.i)+':'+o.lv+':'+o.t.length+(o.v?':'+o.v.length:'')+(o.hl?'*':'')), empty:P('').length+P(null).length+P([]).length, max:P(new Array(60).join('a\n')).length}; });
  check('S07-03: codec da árvore: Tab/2 espaços = nível (até 3, nunca pula um degrau), “ = valor” vira o valor, “[*]” marca o caminho, marcador “-” ignorado, linha vazia some, “= ” vazio não cria valor; texto ↔ itens estável; arrays guardam .i, nulos/vazios/objetos caem, nível e tamanhos com clamp (160/40), no máximo 40 itens', JSON.stringify(tc.items)==='["0:Pergunta=100*","1:Hipótese A*","1:Hipótese B","2:Pulo (vira 2)","3:Nível 3","3:Nível 4 (vira 3)","0:Marcador","0:Sem valor =","0:Receita=R$ 12 M"]'&&tc.rt&&tc.txt==='      Nível 3'&&JSON.stringify(tc.idx)==='["0:0:2:1*","3:1:4*","-:0:4:1*","6:0:160:40"]'&&tc.empty===0&&tc.max===40, tc);

  /* ---------- 2. gaveta de modelos: categorias, prévias, pílulas, busca ---------- */
  await p.click('#bModels'); await sleep(900);
  const dr=await p.evaluate((KINDS)=>{ const cats={}, order=[]; document.querySelectorAll('#modelsBody .dcat').forEach(c=>{ order.push(c.dataset.cat); cats[c.dataset.cat]=[...c.nextElementSibling.querySelectorAll('.fxi')].map(x=>x.dataset.k); }); const cards={}; KINDS.forEach(k=>{ const c=document.querySelector('#modelsBody .fxi[data-k='+k+']'); cards[k]=c?{pv:!!c.querySelector('.pv .am-stage .fx'), pills:c.querySelectorAll('.vl span').length, name:c.querySelector('.ft b').textContent}:null; }); return {order,cats,cards}; },KINDS);
  const srch={}; for(const [q,exp] of [['gantt',['gantt']],['pdca',['pdca']],['porter',['porter']],['bcg',['bcg']],['mece',['issuetree']],['horizontes',['roadmap']],['situação atual',['asistobe']],['caminho crítico',['gantt','roadmap']]]){ await p.fill('#mSearch',q); await sleep(250); srch[q]=await p.evaluate(()=>[...document.querySelectorAll('#modelsBody .fxi')].filter(c=>c.style.display!=='none').map(c=>c.dataset.k).sort()); srch[q+'_ok']=JSON.stringify(srch[q])===JSON.stringify(exp.slice().sort()); }
  await p.fill('#mSearch',''); await sleep(200); await p.evaluate(()=>{ const c=document.querySelector('#modelsBody .dcat[data-cat=Estratégia]'); c&&c.scrollIntoView(); }); await sleep(400); await p.screenshot({path:SH('01-gaveta')}); await p.click('#bFxClose'); await sleep(300);
  check('S07-04: gaveta Modelos: PDCA em Processos; Gantt, AS-IS → TO-BE e roadmap em Evolução; Porter, árvore e BCG em Estratégia (ordem Matrizes… Estratégia, Processos… Evolução…), cada card com prévia viva, nome e 3–4 pílulas de efeito; buscas “gantt”, “pdca”, “porter”, “bcg”, “mece”, “horizontes”, “situação atual” acham só o modelo certo e “caminho crítico” acha Gantt e roadmap', dr.order.indexOf('Estratégia')>0&&dr.order.indexOf('Estratégia')<dr.order.indexOf('Processos')&&dr.order.indexOf('Processos')<dr.order.indexOf('Evolução')&&KINDS.every(k=>(dr.cats[CAT[k]]||[]).indexOf(k)>=0&&dr.cards[k]&&dr.cards[k].pv&&dr.cards[k].pills>=3&&dr.cards[k].pills<=4)&&Object.keys(srch).filter(k=>/_ok$/.test(k)).every(k=>srch[k]), {dr,srch});

  /* ---------- 3. inserir cada modelo: elemento, efeito padrão, painel (chips + campos com o codec certo) ---------- */
  const ins={};
  for(const k of KINDS){ await fresh(p); await p.evaluate(k=>AMStudio.insertFx(k),k); await sleep(350);
    ins[k]=await p.evaluate((k)=>{ const e=AMStudio.deck.slides[0].els[0], F=AMRT.FX[k], q=s=>document.querySelector('#props '+s); return {kind:e.kind, v:e.variant, dv:F.variant, panel:e.data.panel, n:AMStudio.deck.slides[0].els.length, name:q('.ph h2').firstChild.textContent, chips:[...document.querySelectorAll('#props [data-var]')].map(x=>x.dataset.var).join(','), vars:F.variants.map(v=>v[0]).join(','), codecs:[...document.querySelectorAll('#props [data-p^="data."]')].map(x=>x.dataset.p.slice(5)+':'+(x.dataset.codec||x.tagName.toLowerCase()+(x.type?'/'+x.type:''))), stage:!!document.querySelector('#wrap .am-stage .am-el .fx'), zoom:q('[data-set=zoom]')&&/\bon\b/.test(q('[data-set=zoom]').className), tip:!!q('.vtip')}; },k);
    if(k==='gantt') await p.screenshot({path:SH('02-painel-gantt')}); }
  check('S07-05: insertFx de cada modelo cria 1 elemento no efeito padrão, sem painel branco em slide claro, renderizado no palco; o painel mostra o nome do modelo, os chips de efeito (na ordem do registro), a dica, “Ampliar na apresentação” ligado e os campos de Conteúdo com o codec certo (Gantt: períodos lines, atividades rows:t|s|e|k, hoje texto; árvore: outline com data-maxlv=3; BCG: unidades rows + quadrantes lines)', KINDS.every(k=>ins[k].kind===k&&ins[k].v===ins[k].dv&&ins[k].panel==null&&ins[k].n===1&&ins[k].stage&&ins[k].chips===ins[k].vars&&ins[k].zoom&&ins[k].tip&&ins[k].name===ins[k].name)&&ins.gantt.codecs.join('|')==='periods:lines|tasks:rows:t|s|e|k|today:input/text'&&ins.issuetree.codecs.join('|')==='items:outline'&&ins.bcg.codecs.join('|')==='items:rows:t|x:n|y:n|s:n|tx:n|ty:n|q:lines|xlab:input/text|ylab:input/text'&&ins.pdca.codecs.length===7, ins);
  const mx=await p.evaluate(()=>{ AMStudio.insertFx('issuetree'); const t=document.querySelector('#props textarea[data-codec=outline]'); return {maxlv:t&&t.dataset.maxlv, txt:t&&t.value, hint:(document.querySelector('#props .outl-h')||{}).textContent||''}; });
  check('S07-06: o painel da árvore usa o codec do modelo: textarea outline com data-maxlv=3, texto = treeText dos itens (“[*]” nos nós do caminho) e a dica cita “até 3”', mx.maxlv==='3'&&mx.txt==='Como elevar o EBITDA em 20% até 2027? [*]\n  Aumentar a receita [*]\n    Reajustar preços nos segmentos premium [*]\n    Ampliar a carteira B2B\n  Reduzir custos\n    Renegociar contratos de insumos\n    Automatizar o back-office\n  Otimizar o capital\n    Reduzir estoques em 15 dias'&&/até 3/.test(mx.hint), mx);

  /* ---------- 4. Gantt: linhas, fases, marcos, críticas, hoje; posições por rótulo pelo painel; efeitos; edição no slide ---------- */
  await fresh(p); await p.evaluate(()=>AMStudio.insertFx('gantt')); await sleep(300);
  const gt=await p.evaluate(()=>{ const st=document.querySelector('#wrap .am-stage'), q=s=>st.querySelectorAll(s); const bars=[...q('.gt-b')].map(b=>b.style.left+'/'+b.style.width); return {rows:q('.gt-r').length, phases:q('.gt-r.f').length, ms:q('.gt-ms').length, crit:q('.gt-b.c').length, fut:q('.gt-b.fut').length, today:q('.gt-today').length, tx:getComputedStyle(st.querySelector('.gt-today')).getPropertyValue('--x').trim(), periods:q('.gt-ps [data-e]').length, bar2:bars[2], pill:st.querySelector('.gt-today span').textContent, g:[...q('.gt-r')].map(r=>r.dataset.g).join('')}; });
  await p.fill('#props textarea[data-codec="rows:t|s|e|k"]','Kickoff | Jan | Jan | m\nOnda 1 | Fev | Abr | c\nPiloto | S3 | 15/04 |\nFase final | 5 | 6 | f'); await sleep(250);
  await p.fill('#props input[data-p="data.today"]','Mar'); await sleep(250);
  const gl=await p.evaluate(()=>{ const st=document.querySelector('#wrap .am-stage'), e=AMStudio.deck.slides[0].els[0], r=s=>Math.round(parseFloat(s)*100)/100; const B=[...st.querySelectorAll('.gt-tr > i')]; return {s:e.data.tasks.map(t=>t.s+'>'+t.e).join(','), today:e.data.today, ms:B[0].className+'@'+r(B[0].style.left), onda:r(B[1].style.left)+'/'+r(B[1].style.width), piloto:r(B[2].style.left)+'/'+r(B[2].style.width), fase:B[3].className+'@'+r(B[3].style.left)+'/'+r(B[3].style.width), tx:r(getComputedStyle(st.querySelector('.gt-today')).getPropertyValue('--x'))}; });
  check('S07-07: Gantt padrão: 9 linhas (3 fases, 2 marcos, 3 críticas), 2 barras depois do “hoje” (2,4 → linha em 40 %), pílula “hoje”, 6 períodos editáveis, grupos por fase (data-g 000111222); pelo painel, rótulos viram posições: marco em “Jan” = 0 %, “Fev”→“Abr” = 16,67 % a 50 %, “S3”→“15/04” = 33,33 % + 24,19 %, fase 5→6; “hoje” = “Mar” = 33,33 %', gt.rows===9&&gt.phases===3&&gt.ms===2&&gt.crit===3&&gt.fut===2&&gt.today===1&&gt.tx==='40.000%'&&gt.periods===6&&gt.bar2==='12.5%/12.5%'&&gt.pill==='hoje'&&gt.g==='000111222'&&gl.s==='Jan>Jan,Fev>Abr,S3>15/04,5>6'&&gl.today==='Mar'&&gl.ms==='gt-ms@0'&&gl.onda==='16.67/50'&&gl.piloto==='33.33/24.19'&&gl.fase==='gt-b f fut@83.33/16.67'&&gl.tx===33.33, {gt,gl});
  const gv=await p.evaluate(async()=>{ const out={}; const run=async(v,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('gantt',v)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=(n,ps)=>getComputedStyle(n,ps||null);
    let st=await run('bars',60); out.bars={a:cs(st.querySelectorAll('.gt-b')[1]).animationName, d:cs(st.querySelectorAll('.gt-b')[1]).animationDelay, ms:cs(st.querySelector('.gt-ms')).animationName};
    st=await run('phase',60); out.phase={d:cs(st.querySelectorAll('.gt-r')[4].querySelector('.gt-b')).animationDelay};
    st=await run('today',60); out.today={line:cs(st.querySelector('.gt-today'),'::before').animationName, pill:cs(st.querySelector('.gt-today span')).animationName, fut:cs(st.querySelector('.gt-b.fut')).animationName};
    st=await run('critical',2600); out.critical={c:cs(st.querySelector('.gt-b.c')).animationName, o:cs(st.querySelector('.gt-r:not(.c):not(.f) .gt-b')).animationName, bg:cs(st.querySelector('.gt-b.c')).backgroundColor, dim:cs(st.querySelector('.gt-r:not(.c):not(.f) .gt-b')).opacity};
    return out; });
  await p.screenshot({path:SH('03-gantt-critico')});
  check('S07-08: efeitos do Gantt: “Barras crescendo” (amBar, 2ª linha a 0,32 s, marcos m7Ms); “Fase a fase” (linha 5 = fase 1 → 0,94 s); “Linha do hoje” (m7Sweep na linha e na pílula, barras futuras m7Fut); “Caminho crítico” (barras críticas m7Crit → laranja, demais m7Fut → 0,35)', gv.bars.a==='amBar'&&gv.bars.d==='0.32s'&&gv.bars.ms==='m7Ms'&&gv.phase.d==='0.94s'&&gv.today.line==='m7Sweep'&&gv.today.pill==='m7Sweep'&&/m7Fut/.test(gv.today.fut)&&/m7Crit/.test(gv.critical.c)&&/m7Fut/.test(gv.critical.o)&&gv.critical.bg==='rgb(247, 140, 22)'&&+gv.critical.dim<.4, gv);
  await p.evaluate(()=>window.__labOff());
  const tsp=await p.$('#wrap .am-stage [data-e="tasks.1.t"]'); const tb=await tsp.boundingBox(); await p.mouse.dblclick(tb.x+tb.width/2, tb.y+tb.height/2); await sleep(200);
  const ce=await p.evaluate(()=>{ const a=document.activeElement; return {ce:a&&a.isContentEditable, path:a&&a.dataset.e}; });
  await p.keyboard.type('Onda piloto'); await p.keyboard.press('Enter'); await sleep(300);
  const ie=await p.evaluate(()=>({t:AMStudio.deck.slides[0].els[0].data.tasks[1].t, shown:document.querySelector('#wrap .am-stage [data-e="tasks.1.t"]').textContent, ta:document.querySelector('#props textarea[data-codec="rows:t|s|e|k"]').value.split('\n')[1]}));
  check('S07-09: duplo clique num nome de atividade edita no slide (contenteditable em tasks.1.t); Enter grava, redesenha e o painel acompanha a linha', ce.ce&&ce.path==='tasks.1.t'&&ie.t==='Onda piloto'&&ie.shown==='Onda piloto'&&/^Onda piloto \| Fev \| Abr \| c$/.test(ie.ta), {ce,ie});

  /* ---------- 5. PDCA, AS-IS → TO-BE, Porter: peças e efeitos ---------- */
  const pd=await p.evaluate(async()=>{ const out={}; const run=async(v,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('pdca',v)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('cycle',60); out.q=[...st.querySelectorAll('.pd-q path')].map(x=>x.getAttribute('fill')).join(','); out.let=[...st.querySelectorAll('.pd-q text')].map(x=>x.textContent).join(''); out.lists=[...st.querySelectorAll('.pd-l')].map(l=>l.querySelector('b').textContent+':'+l.querySelectorAll('li').length).join(','); out.center=st.querySelector('.pd-c [data-e]').textContent; out.cyc={q:cs(st.querySelectorAll('.pd-q')[2]).animationName, d:cs(st.querySelectorAll('.pd-q')[2]).animationDelay, li:cs(st.querySelector('.pd-l li')).animationName}; out.ramp0=st.querySelectorAll('.pd-ramp').length;
    st=await run('spin',60); out.spin=cs(st.querySelector('.pd-w')).animationName;
    st=await run('ramp',60); out.ramp={w:cs(st.querySelector('.pd-w')).animationName, ramp:st.querySelectorAll('.pd-ramp').length, chock:st.querySelectorAll('.pd-chock').length, lab:st.querySelector('text.pd-chock').textContent, ch:cs(st.querySelector('path.pd-chock')).animationName};
    st=await run('focus',2500); out.focus={cycle:st.querySelector('.fxpd').dataset.cycle, active:st.querySelector('.fxpd').classList.contains('cy-active'), on:st.querySelectorAll('.cy-on').length, dim:+cs(st.querySelector('.pd-l:not(.cy-on)')).opacity};
    return out; });
  await p.screenshot({path:SH('04-pdca-foco')}); await p.evaluate(()=>window.__labOff());
  check('S07-10: PDCA: 4 quadrantes navy / aço / aço claro / laranja com as letras P D C A, 4 listas nomeadas com 2 ações, centro “Melhoria contínua”; “Fase a fase” (amZoom, C a 0,6 s, ações amRise); “Roda girando” (m7Spin); “Subindo a rampa” (m7Roll, rampa, calço m7Chock com o rótulo “padrão”, sem rampa nas outras); “Foco percorrendo” (data-cycle, quadrante + lista acesos, resto a 0,3)', pd.q==='#002A46,#4A6FA5,#7EA1C3,#F78C16'&&pd.let==='PDCA'&&pd.lists==='Planejar:2,Executar:2,Verificar:2,Agir:2'&&pd.center==='Melhoria contínua'&&pd.cyc.q==='amZoom'&&pd.cyc.d==='0.6s'&&pd.cyc.li==='amRise'&&pd.ramp0===0&&pd.spin==='m7Spin'&&pd.ramp.w==='m7Roll'&&pd.ramp.ramp===1&&pd.ramp.chock===2&&pd.ramp.lab==='padrão'&&pd.ramp.ch==='m7Chock'&&pd.focus.cycle==='g'&&pd.focus.active&&pd.focus.on===2&&pd.focus.dim<.5, pd);
  const ab=await p.evaluate(async()=>{ const out={}; const run=async(v,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('asistobe',v)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('reveal',60); out.n=[st.querySelectorAll('.ab-t').length,st.querySelectorAll('.ab-a').length,st.querySelectorAll('.ab-ar').length,st.querySelectorAll('.ab-b').length].join('/'); out.heads=[...st.querySelectorAll('.ab-h')].map(h=>h.textContent).join('|'); out.reveal={a:cs(st.querySelector('.ab-a')).animationName, ar:cs(st.querySelector('.ab-ar')).animationName, b:cs(st.querySelector('.ab-b')).animationName, bd:cs(st.querySelector('.ab-b')).animationDelay, bg:cs(st.querySelector('.ab-b')).backgroundColor};
    st=await run('rows',60); out.rows={d2:cs(st.querySelectorAll('.ab-a')[2]).animationDelay, b2:cs(st.querySelectorAll('.ab-b')[2]).animationDelay};
    st=await run('flip',60); out.flip=cs(st.querySelector('.ab-b')).animationName;
    st=await run('focus',2500); out.focus={cycle:st.querySelector('.fxab').dataset.cycle, on:st.querySelectorAll('.cy-on').length, active:st.querySelector('.fxab').classList.contains('cy-active')};
    return out; });
  await p.evaluate(()=>window.__labOff());
  check('S07-11: AS-IS → TO-BE: 4 dimensões = 4 rótulos + 4 cards gelo + 4 setas + 4 cards navy, cabeçalhos “Hoje (AS-IS)” / “Futuro (TO-BE)”; “Hoje, depois o futuro” (AS-IS amLeft, setas amBar, TO-BE amWipe a 1,25 s); “Linha a linha” (3ª linha a 1,3 s / 1,75 s); “Virada” (amFlip); “Foco percorrendo” (uma dimensão = 4 peças acesas)', ab.n==='4/4/4/4'&&ab.heads==='Hoje (AS-IS)|Futuro (TO-BE)'&&ab.reveal.a==='amLeft'&&ab.reveal.ar==='amBar'&&ab.reveal.b==='amWipe'&&ab.reveal.bd==='1.25s'&&ab.reveal.bg==='rgb(0, 42, 70)'&&ab.rows.d2==='1.3s'&&ab.rows.b2==='1.75s'&&ab.flip==='amFlip'&&ab.focus.cycle==='g'&&ab.focus.on===4&&ab.focus.active, ab);
  const pt=await p.evaluate(async()=>{ const out={}; const run=async(v,sc,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('porter',v,false,sc)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('converge',1,60); out.f=st.querySelectorAll('.pt-f').length; out.hi=[...st.querySelectorAll('.pt-f')].map(f=>f.classList.contains('hi')?1:0).join(''); out.dots=[...st.querySelectorAll('.pt-f .pt-dots')].map(d=>d.querySelectorAll('i.on').length).join(''); out.cdots=st.querySelector('.pt-c .pt-dots').querySelectorAll('i.on').length; out.arrows=st.querySelectorAll('.pt-a').length; out.hiArrows=st.querySelectorAll('.pt-a.hi').length; out.sw=[...st.querySelectorAll('.pt-l')].map(l=>l.getAttribute('stroke-width')).join(','); out.cmt=st.querySelectorAll('.pt-f > span:not(.pt-dots)').length; out.anim={c:cs(st.querySelector('.pt-c')).animationName, f:cs(st.querySelectorAll('.pt-f')[3]).animationDelay, l:cs(st.querySelector('.pt-l')).animationName, hiStroke:cs(st.querySelector('.pt-a.hi .pt-l')).stroke, loStroke:cs(st.querySelector('.pt-a:not(.hi) .pt-l')).stroke};
    st=await run('pressure',1,60); out.psw=[...st.querySelectorAll('.pt-l')].map(l=>l.getAttribute('stroke-width')).join(','); out.pulse=cs(st.querySelector('.pt-a.hi')).animationName;
    st=await run('converge',.4,60); out.small={cmt:st.querySelectorAll('.pt-f > span:not(.pt-dots)').length, f:st.querySelectorAll('.pt-f').length};
    st=await run('focus',1,2500); out.focus={cycle:st.querySelector('.fxpt').dataset.cycle, on:st.querySelectorAll('.cy-on').length};
    return out; });
  await p.evaluate(()=>window.__labOff());
  check('S07-12: Porter: 4 forças + centro, medidor de 5 pontos (2/4/3/5, rivalidade 4), forças ≥ 4 com contorno e seta laranja (fornecedores, substitutos), 4 setas de 3 px desenhando (amDraw) depois do centro (amZoom) e dos cards (4º a 1,06 s); “Pressão por intensidade” (espessuras 4,8/7,6/6,2/9 e pulso m7Pulse nas altas); numa caixa pequena (40 %) o comentário sai e ficam nome + intensidade; “Foco percorrendo” acende força + seta', pt.f===4&&pt.hi==='0101'&&pt.dots==='2435'&&pt.cdots===4&&pt.arrows===4&&pt.hiArrows===2&&pt.sw==='3.0,3.0,3.0,3.0'&&pt.cmt===4&&pt.anim.c==='amZoom'&&pt.anim.f==='1.06s'&&pt.anim.l==='amDraw'&&pt.anim.hiStroke==='rgb(247, 140, 22)'&&pt.anim.loStroke==='rgb(126, 161, 195)'&&pt.psw==='4.8,7.6,6.2,9.0'&&pt.pulse==='m7Pulse'&&pt.small.cmt===0&&pt.small.f===4&&pt.focus.cycle==='g'&&pt.focus.on===2, pt);

  /* ---------- 6. Roadmap, árvore e BCG: peças e efeitos ---------- */
  const rm=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('roadmap',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('lanes',null,60); const ch=[...st.querySelectorAll('.rm-ch')]; out.n={cols:st.querySelectorAll('.rm-hd > span').length, lanes:st.querySelectorAll('.rm-ln').length, ch:ch.length, c:st.querySelectorAll('.rm-ch.c').length, ms:st.querySelectorAll('.rm-ms').length, cn:st.querySelectorAll('.rm-cn').length, alt:st.querySelectorAll('.rm-ln.alt').length}; out.stack=ch.filter(c=>c.dataset.g==='1').map(c=>Math.round(parseFloat(c.style.top))).join(','); out.g=ch.map(c=>c.dataset.g).join(''); out.cbg=cs(st.querySelector('.rm-ch.c')).backgroundColor; out.lanes={ln:cs(st.querySelectorAll('.rm-ln')[2]).animationDelay, ch:cs(ch[ch.length-1]).animationName, cnd:cs(st.querySelector('.rm-cn')).display, sw:cs(st.querySelector('.rm-sw')).display}; out.msLab=st.querySelector('.rm-ms span').textContent;
    st=await run('waves',null,60); out.waves={sw:cs(st.querySelector('.rm-sw')).display, swa:cs(st.querySelector('.rm-sw')).animationName, ch:cs(st.querySelector('.rm-ch')).animationName, d:cs([...st.querySelectorAll('.rm-ch')].filter(c=>/Escala/.test(c.textContent))[0]).animationDelay};
    st=await run('path',null,60); out.path={cnd:cs(st.querySelector('.rm-cn')).display, cna:cs(st.querySelectorAll('.rm-cn')[1]).animationName, c:cs(st.querySelector('.rm-ch.c')).animationName, d1:cs([...st.querySelectorAll('.rm-ch.c')].filter(c=>/Escala/.test(c.textContent))[0]).animationDelay, vert:[...st.querySelectorAll('.rm-cn')].every(c=>/^M[\d. ]+V[\d.]+$/.test(c.getAttribute('d')))};
    st=await run('lanes',{cols:['H1','H2','H3'],lanes:['A','B'],items:[{t:'Marco no fim',l:2,s:2.9,e:2.9,k:'m'},{t:'Longa',l:1,s:0,e:.8,k:'c'},{t:'Curta',l:9,s:1,e:1.5,k:'c'}]},60); out.alt={ms:st.querySelector('.rm-ms').classList.contains('r'), lanes:st.querySelectorAll('.rm-ln').length, lane9:st.querySelectorAll('.rm-ch[data-g="1"]').length, cn:st.querySelectorAll('.rm-cn').length, elbow:/H[\d.]+V[\d.]+H[\d.]+$/.test(st.querySelector('.rm-cn').getAttribute('d'))};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxrm').dataset.cycle, on:st.querySelectorAll('.cy-on').length, active:st.querySelector('.fxrm').classList.contains('cy-active')};
    return out; });
  await p.screenshot({path:SH('05-roadmap-foco')}); await p.evaluate(()=>window.__labOff());
  check('S07-13: roadmap: 3 ondas, 3 trilhas (a do meio em gelo), 7 chips (3 em laranja) + 1 marco, os dois chips sobrepostos no tempo da trilha 2 em sub-linhas diferentes; “Trilha a trilha” (trilha 3 a 0,9 s, chips amRise, sem conectores nem varredura); “Onda a onda” (varredura m7Wave, chips amWipe, “Escala nacional” a 1,7 s); “Caminho crítico” (conectores visíveis, elos verticais entre destaques sobrepostos, m7Light nos chips em sequência); dados alternativos: marco no fim vira rótulo à esquerda, trilha 9 cai na última, destaques afastados ligados por cotovelo; “Foco percorrendo” acende uma trilha inteira (faixa + chips)', rm.n.cols===3&&rm.n.lanes===3&&rm.n.ch===7&&rm.n.c===3&&rm.n.ms===1&&rm.n.cn===2&&rm.n.alt===1&&rm.stack.split(',').length===3&&new Set(rm.stack.split(',')).size===2&&rm.g==='0011122'&&rm.cbg==='rgb(247, 140, 22)'&&rm.lanes.ln==='0.9s'&&rm.lanes.ch==='amRise'&&rm.lanes.cnd==='none'&&rm.lanes.sw==='none'&&rm.msLab==='Go-live do piloto'&&rm.waves.sw==='block'&&rm.waves.swa==='m7Wave'&&rm.waves.ch==='amWipe'&&Math.abs(parseFloat(rm.waves.d)-1.7)<.01&&rm.path.cnd==='block'&&rm.path.cna==='m7WipeR'&&/m7Light/.test(rm.path.c)&&/2\.4s/.test(rm.path.d1)&&rm.path.vert&&rm.alt.ms&&rm.alt.lanes===2&&rm.alt.lane9===1&&rm.alt.cn===1&&rm.alt.elbow&&rm.focus.cycle==='g'&&rm.focus.active&&rm.focus.on>=3, rm);
  const it=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('issuetree',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('branch',null,60); const N=[...st.querySelectorAll('.it-n')]; out.n={nodes:N.length, d:[0,1,2,3].map(d=>st.querySelectorAll('.it-n.d'+d).length).join(''), c:st.querySelectorAll('.it-c').length, hl:st.querySelectorAll('.it-n.hl').length, chl:st.querySelectorAll('.it-c.hl').length, rootG:N.filter(n=>n.classList.contains('d0'))[0].hasAttribute('data-g'), g1:N.filter(n=>n.classList.contains('d1')).map(n=>n.dataset.g).join(''), rootHl:st.querySelector('.fxit').classList.contains('it-hl'), v:st.querySelectorAll('.it-v').length}; out.branch={n2:cs(N.filter(n=>n.classList.contains('d2'))[0]).animationDelay, c:cs(st.querySelector('.it-c')).animationName, c2:cs([...st.querySelectorAll('.it-c')].filter(c=>c.style.getPropertyValue('--lv')==='2')[0]).animationDelay};
    const ys=N.filter(n=>n.classList.contains('d2')).map(n=>parseFloat(n.style.top)); out.sorted=ys.every((y,i)=>!i||y>ys[i-1]);
    st=await run('grow',null,60); out.grow={n:cs(st.querySelector('.it-n.d1')).animationName, c:cs(st.querySelector('.it-c')).animationName, cd:cs(st.querySelector('.it-c')).animationDelay};
    st=await run('path',null,2300); out.path={dim:cs(st.querySelector('.it-n.d1:not(.hl)')).opacity, hot:cs(st.querySelector('.it-c.hl')).stroke, ring:/247, 140, 22/.test(cs(st.querySelector('.it-n.d1.hl')).boxShadow), rootOp:cs(st.querySelector('.it-n.d0')).opacity};
    st=await run('path',{items:[{t:'A',lv:0},{t:'B',lv:1}]},60); out.noHl={cls:st.querySelector('.fxit').classList.contains('it-hl'), anim:cs(st.querySelector('.it-n.d1')).animationName};
    st=await run('branch',{items:AMRT.treeParse('Receita = 120 [*]\n  Preço = 80 [*]\n    Mix premium = 30\n      Lançamentos = 10\n  Volume = 40')},60); out.kpi={v:st.querySelectorAll('.it-v').length, mono:/Mono/.test(cs(st.querySelector('.it-v')).fontFamily), d3:st.querySelectorAll('.it-n.d3').length, txt:st.querySelector('.it-n.d0').textContent};
    st=await run('branch',{items:[]},60); out.empty={n:st.querySelectorAll('.it-n').length, msg:!!st.querySelector('.it-empty')};
    st=await run('focus',null,2500); out.focus={cycle:st.querySelector('.fxit').dataset.cycle, on:st.querySelectorAll('.cy-on').length, root:cs(st.querySelector('.it-n.d0')).opacity};
    return out; });
  await p.evaluate(()=>window.__labOff());
  check('S07-14: árvore: 9 nós em 3 colunas (1/3/5), 8 conectores em cotovelo, 3 nós e 2 conectores no caminho [*], raiz sem data-g e ramos 0/1/2, folhas em ordem; “Nível a nível” (nível 2 a 1 s, conectores amDraw, para o nível 2 a 0,75 s); “Ramos crescendo” (conectores amDraw a partir de 0,58 s no 1º ramo, nós amPop); “Caminho em destaque” (o resto a 0,35, conectores e anéis laranja, raiz inteira; sem [*] nada esmaece); “Receita = 120” vira árvore de KPIs (valores mono, 4 níveis); sem itens só o lembrete; “Foco percorrendo” por ramo com a raiz sempre acesa', it.n.nodes===9&&it.n.d==='1350'&&it.n.c===8&&it.n.hl===3&&it.n.chl===2&&!it.n.rootG&&it.n.g1==='012'&&it.n.rootHl&&it.n.v===0&&it.branch.n2==='1s'&&it.branch.c==='amDraw'&&it.branch.c2==='0.75s'&&it.sorted&&it.grow.n==='amPop'&&it.grow.c==='amDraw'&&it.grow.cd==='0.58s'&&+it.path.dim<.4&&it.path.hot==='rgb(247, 140, 22)'&&it.path.ring&&+it.path.rootOp>.95&&!it.noHl.cls&&it.noHl.anim==='amFade'&&it.kpi.v===5&&it.kpi.mono&&it.kpi.d3===1&&it.kpi.txt==='Receita120'&&it.empty.n===0&&it.empty.msg&&it.focus.cycle==='g'&&it.focus.on>=2&&+it.focus.root>.95, it);
  const bc=await p.evaluate(async()=>{ const out={}; const run=async(v,data,wait)=>{ window.__lab({bg:'#fff',els:[window.__el('bcg',v,false,1,data)]},true); await new Promise(r=>setTimeout(r,wait)); return document.querySelector('#s7lab .am-stage'); }; const cs=n=>getComputedStyle(n);
    let st=await run('drop',null,60); const B=[...st.querySelectorAll('.bc-b')], LB=[...st.querySelectorAll('.bc-lb')]; out.q=[...st.querySelectorAll('.bc-q')].map(q=>q.textContent).join('|'); out.b=B.length; out.w=B.map(b=>Math.round(parseFloat(b.style.width)*10)/10); out.big=B.map((b,i)=>[parseFloat(b.style.width),i]).sort((a,b)=>b[0]-a[0])[0][1]; out.col=B.map(b=>cs(b).backgroundColor).join('|'); out.g=B.map(b=>b.dataset.g).join(''); out.left=Math.round(parseFloat(B[0].style.left)); out.lbSide=LB.map(l=>l.classList.contains('l')?'L':'R').join(''); out.ar=st.querySelectorAll('.bc-ar').length; out.arL=st.querySelectorAll('.bc-ar.l').length; out.gh=[st.querySelectorAll('.bc-gh').length, cs(st.querySelector('.bc-gh')).display]; out.drop={b:cs(B[1]).animationName, d:cs(B[1]).animationDelay, q:cs(st.querySelector('.bc-q')).animationName, ar:cs(st.querySelector('.bc-ar')).animationName}; out.x=st.querySelector('.bc-x').textContent; out.y=st.querySelector('.bc-y').textContent;
    st=await run('grow',null,60); out.grow={b:cs(st.querySelector('.bc-b')).animationName, big:cs([...st.querySelectorAll('.bc-b')][2]).animationDelay, small:cs([...st.querySelectorAll('.bc-b')][3]).animationDelay};
    st=await run('move',null,3300); out.move={gh:cs(st.querySelector('.bc-gh')).display, op:+cs(st.querySelector('.bc-gh')).opacity, a:cs(st.querySelector('.bc-gh')).animationName};
    st=await run('quadrants',null,60); out.quad={q:cs(st.querySelector('.bc-q')).animationName, b:cs(st.querySelector('.bc-b')).animationName, d:cs([...st.querySelectorAll('.bc-b')].filter(b=>b.dataset.g==='3')[0]).animationDelay};
    st=await run('drop',{items:[{t:'Só um',x:50,y:50,s:0}],q:['A','B','C','D'],xlab:'x',ylab:'y'},60); out.one={b:st.querySelectorAll('.bc-b').length, w:parseFloat(st.querySelector('.bc-b').style.width)>0, g:st.querySelector('.bc-b').dataset.g, ar:st.querySelectorAll('.bc-ar').length};
    return out; });
  await p.screenshot({path:SH('06-bcg-quadrantes')}); await p.evaluate(()=>window.__labOff());
  check('S07-15: BCG: quadrantes Estrelas / Pontos de interrogação / Vacas leiteiras / Abacaxis, 5 bolhas com raio ∝ √receita (Atacado a maior), cores por quadrante (laranja / aço / navy / aço claro), eixo x invertido (Linha premium, 78 % → 22 % da esquerda), rótulos do lado oposto à seta, 2 setas de meta (uma para a esquerda) e 2 fantasmas só em “Rumo à meta” (opacidade 0,45 ao fim); “Bolhas pousando” (amDropC, 2ª a 0,76 s, setas m7WipeL/R); “Por tamanho” (amPopC, maior a 0,5 s, menor a 1,38 s); “Quadrante a quadrante” (amZoom, abacaxi a 1,74 s); 1 unidade sem receita ainda tem bolha, na origem (quadrante 0) e sem seta', bc.q==='Estrelas|Pontos de interrogação|Vacas leiteiras|Abacaxis'&&bc.b===5&&bc.big===2&&bc.col==='rgb(247, 140, 22)|rgb(74, 111, 165)|rgb(0, 42, 70)|rgb(163, 184, 214)|rgb(74, 111, 165)'&&bc.g==='01231'&&bc.left===22&&bc.lbSide==='RRRLR'&&bc.ar===2&&bc.arL===2&&bc.gh[0]===2&&bc.gh[1]==='none'&&bc.drop.b==='amDropC'&&bc.drop.d==='0.76s'&&bc.drop.q==='amFade'&&bc.drop.ar==='m7WipeL'&&/alta/.test(bc.x)&&/baixa/.test(bc.x)&&/Crescimento/.test(bc.y)&&bc.grow.b==='amPopC'&&bc.grow.big==='0.5s'&&bc.grow.small==='1.38s'&&bc.move.gh==='block'&&Math.abs(bc.move.op-.45)<.02&&bc.move.a==='m7Ghost'&&bc.quad.q==='amZoom'&&bc.quad.b==='amPopC'&&bc.quad.d==='1.74s'&&bc.one.b===1&&bc.one.w&&bc.one.g==='0'&&bc.one.ar===0, bc);

  /* ---------- 7. nada cortado nem fora da caixa: 7 modelos × branco/navy (painel) × 100 %/50 %; paleta A&M ---------- */
  const fitIssues=[], bad=[]; let nFit=0;
  for(const k of KINDS) for(const dark of [false,true]) for(const sc of [1,.5]){
    await lab(p,k,null,dark,sc,null,null); nFit++;
    const iss=await stageCheck(p,'#s7lab .am-stage'); if(iss.length) fitIssues.push(k+(dark?' navy':'')+' '+(sc*100)+'%: '+iss.join('; '));
    const pal=await p.evaluate(([k,PAL])=>{ const st=document.querySelector('#s7lab .am-stage'), out=[]; const hex=c=>{ const m=/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)$/.exec(c); if(!m) return c.toUpperCase(); if(m[4]==='0') return 'NONE'; return '#'+[m[1],m[2],m[3]].map(x=>(+x).toString(16).padStart(2,'0')).join('').toUpperCase(); };
      st.querySelectorAll('.fx *').forEach(x=>{ const cs=getComputedStyle(x); [cs.backgroundColor, cs.color].forEach(c=>{ const h=hex(c); if(PAL.indexOf(h)<0) out.push(k+':'+x.className+':'+h); }); if(x instanceof SVGElement&&/^(path|rect|circle|text|line|polygon)$/i.test(x.tagName)){ ['fill','stroke'].forEach(a=>{ const v=x.getAttribute(a); if(v&&PAL.indexOf(v.toUpperCase())<0) out.push(k+':'+a+':'+v); const c=hex(cs[a]); if(c!=='NONE'&&PAL.indexOf(c)<0) out.push(k+':'+a+'~'+c); }); } });
      return out; },[k,PAL]); bad.push(...pal);
    if(sc===1&&!dark) await p.screenshot({path:SH('10-'+k)}); if(sc===1&&dark&&(k==='gantt'||k==='bcg')) await p.screenshot({path:SH('11-'+k+'-navy')}); }
  await p.evaluate(()=>window.__labOff());
  check('S07-16: os 7 modelos no tamanho padrão e a 50 %, em slide branco e em navy com painel branco: nenhum texto cortado, nada fora da caixa nem do slide (stageCheck); cores só da paleta A&M (navy, aços, gelos, laranja, branco), nunca vermelho', fitIssues.length===0&&bad.length===0&&nFit===28, {fitIssues,bad:[...new Set(bad)].slice(0,20)});

  /* ---------- 8. dados hostis: html() puro nunca escreve NaN/negativo, texto vira texto, atributos não vazam ---------- */
  const hostile=await p.evaluate(()=>{ const out={}, H=(k,d,w,h)=>AMRT.FX[k].html(d,w,h,{variant:AMRT.FX[k].variant,data:d}); const bad=s=>/NaN|Infinity|undefined|:\s*-\d|onmouseover|<img/.test(s);
    const g=H('gantt',{periods:['<img src=x>','Fev',{},null],today:'nope',tasks:[{t:'<img src=x>',s:'abc',e:NaN,k:'f" onmouseover="x'},{t:7,s:-5,e:99,k:'critical'},null,'texto',{t:'ok',s:'1e9'}]},1160,440); out.g={bad:bad(g), esc:/&lt;img src=x&gt;/.test(g), rows:(g.match(/class="gt-r/g)||[]).length, cls:(g.match(/class="gt-b[^"]*"/g)||[]).join(' '), today:/gt-today/.test(g)};
    const r=H('roadmap',{cols:'A;B',lanes:['L1'],items:[{t:'<b>x</b>',l:'99" onmouseover="',s:'x',e:-1,k:'m'},{t:'y',l:0,s:5,e:1,k:'c'}]},1160,440); out.r={bad:bad(r), esc:/&lt;b&gt;x&lt;\/b&gt;/.test(r), ms:(r.match(/rm-ms/g)||[]).length, cols:(r.match(/rm-hd[^>]*>/)||[''])[0]&&(r.match(/<span style="--k/g)||[]).length};
    const i=H('issuetree',{items:[{t:'<i>',lv:'<b>',v:{},hl:'<x>'},{t:'b',lv:9},{t:'c',lv:-1,v:'<v>'}]},1100,440); out.i={bad:bad(i), nodes:(i.match(/class="it-n/g)||[]).length, lv:(i.match(/it-n d\d/g)||[]).join(','), esc:/&lt;i&gt;/.test(i)&&/&lt;v&gt;/.test(i)};
    const b=H('bcg',{items:[{t:'<s>',x:'1e9',y:-50,s:-5,tx:'x',ty:'y'},{t:'ok',x:50,y:50,s:1e12,tx:51,ty:50}],q:'a;b',xlab:{},ylab:null},900,470); out.b={bad:bad(b), bubbles:(b.match(/class="bc-b /g)||[]).length, arrows:(b.match(/bc-ar/g)||[]).length, esc:/&lt;s&gt;/.test(b)};
    const pd=H('pdca',{p:'a;b;c;d;e;f;g;h',d:[null,'<p>'],c:5,a:{},center:['x'],names:'Só um',letters:[{},'Ⅱ']},40,40); out.pd={bad:bad(pd), lis:(pd.match(/<li /g)||[]).length, esc:/&lt;p&gt;/.test(pd), names:/Só um/.test(pd)&&/Executar/.test(pd)};
    const pt=H('porter',{forces:[{t:'<t>',n:'99',x:1},{n:-3}],center:null,cn:'2,5'},0,-10); out.pt={bad:bad(pt), f:(pt.match(/class="pt-f/g)||[]).length, hi:(pt.match(/pt-f hi/g)||[]).length, esc:/&lt;t&gt;/.test(pt)};
    const ab=H('asistobe',{rows:[{t:'<a>',a:7,b:null},'x',null,{}],from:{},to:1},NaN,NaN); out.ab={bad:bad(ab), rows:(ab.match(/class="ab-t"/g)||[]).length, esc:/&lt;a&gt;/.test(ab)};
    return out; });
  check('S07-17: html() puro com dados hostis (tags, objetos, nulos, NaN, negativos, 1e9, caixa 40×40 / 0×−10 / NaN): nunca escreve NaN/Infinity/undefined nem valor negativo, escapa todo texto, o tipo (k) vira só uma letra válida (nada de atributo injetado), linhas/itens inválidos viram vazios sem quebrar a contagem, nível com clamp, posições com clamp', !out(hostile).some(Boolean)&&hostile.g.esc&&hostile.g.rows===5&&!/onmouseover/.test(hostile.g.cls)&&/gt-b f"/.test(hostile.g.cls)&&!hostile.g.today&&hostile.r.esc&&hostile.r.ms===1&&hostile.r.cols===2&&hostile.i.nodes===3&&hostile.i.lv.split(',').sort().join(',')==='it-n d0,it-n d0,it-n d1'&&hostile.i.esc&&hostile.b.bubbles===2&&hostile.b.arrows>=0&&hostile.b.esc&&hostile.pd.lis===7&&hostile.pd.esc&&hostile.pd.names&&hostile.pt.f===2&&hostile.pt.hi===1&&hostile.pt.esc&&hostile.ab.rows===4&&hostile.ab.esc, hostile);
  function out(h){ return Object.keys(h).map(k=>h[k].bad); }

  /* ---------- 9. vitrine, slide navy (painel branco), apresentação + Ampliar ---------- */
  const gal=await p.evaluate((KINDS)=>{ const it=AMStudio.gallery.items(), fam={}; it.forEach(i=>fam[i.fam]=(fam[i.fam]||0)+1); const ids=it.filter(i=>i.fam==='model').map(i=>i.id); return {ok:KINDS.every(k=>AMRT.FX[k].variants.every(v=>ids.indexOf('model:'+k+':'+v[0])>=0)), n:fam.model, sum:Object.keys(AMRT.FX).filter(k=>AMRT.FX[k].model).reduce((a,k)=>a+AMRT.FX[k].variants.length,0), cats:it.filter(i=>/^model:(pdca|bcg)/.test(i.id)).map(i=>i.cat).join(',')}; },KINDS);
  check('S07-18: a vitrine de efeitos lista cada efeito dos 7 modelos (model:kind:efeito, com a categoria do modelo) e o total da família “Modelos” continua igual à soma dos efeitos de todos os modelos (S01-05)', gal.ok&&gal.n===gal.sum&&gal.cats==='Processos,Processos,Processos,Processos,Estratégia,Estratégia,Estratégia,Estratégia', gal);
  await fresh(p); await p.evaluate(()=>{ AMStudio.addSlide('blank-dark'); AMStudio.insertFx('gantt'); AMStudio.insertFx('bcg',null,{x:640,y:360}); }); await sleep(400);
  const dk=await p.evaluate(()=>{ const e=AMStudio.deck.slides[1].els, st=document.querySelector('#wrap .am-stage'); return {panel:e.map(x=>x.data.panel).join(','), pins:st.querySelectorAll('.fx-panel .fx-pin > .fx').length, dims:e.map(x=>x.w+'x'+x.h).join(',')}; });
  await p.evaluate(()=>{ AMStudio.deck.slides[1].els[1].x=20; AMStudio.deck.slides[1].els[1].y=20; AMStudio.deck.slides[1].els[0].x=600; AMStudio.deck.slides[1].els[0].y=340; AMStudio.deck.slides[1].els[0].w=660; AMStudio.deck.slides[1].els[0].h=360; AMStudio.deck.slides[1].els[1].w=560; AMStudio.deck.slides[1].els[1].h=300; AMStudio.renderAll(); AMStudio.commit(); }); await sleep(400);
  const dkIss=await stageCheck(p,'#wrap .am-stage'); await sleep(2600); await p.screenshot({path:SH('07-navy-painel')});
  check('S07-19: em slide navy os modelos entram no painel branco (.fx-panel > .fx-pin) e, redimensionados (660×360 e 560×300), continuam sem nada cortado nem fora da caixa', dk.panel==='white,white'&&dk.pins===2&&dkIss.length===0, {dk,dkIss});
  await fresh(p); await p.evaluate(()=>{ AMStudio.addSlide('blank-light'); AMStudio.insertFx('pdca',null,{x:300,y:170},'cycle'); AMStudio.insertFx('porter',null,{x:980,y:200},'converge'); AMStudio.insertFx('bcg',null,{x:400,y:560},'drop'); const e=AMStudio.deck.slides[1].els; e[0].w=560; e[0].h=260; e[0].x=20; e[0].y=30; e[1].w=640; e[1].h=320; e[1].x=620; e[1].y=20; e[2].w=600; e[2].h=340; e[2].x=20; e[2].y=360; AMStudio.renderAll(); AMStudio.commit(); AMStudio.goSlide(1); }); await sleep(300);
  await p.keyboard.press('F5'); await sleep(900); await p.keyboard.press('ArrowRight'); await sleep(3200);
  const pres=await p.evaluate(()=>{ const on=document.querySelector('#presenter .amp-slide.on'); return {open:document.getElementById('presenter').classList.contains('open'), pos:document.querySelector('#presenter .amp-pos').textContent.trim(), fx:['.fxpd','.fxpt','.fxbc'].map(s=>on.querySelectorAll(s).length).join(''), visible:[...on.querySelectorAll('.pd-l,.pt-f,.bc-b')].every(x=>+getComputedStyle(x).opacity>.95), zoomables:AMRT.zoomables(AMStudio.deck.slides[1]).map(e=>e.kind).join(',')}; });
  await p.screenshot({path:SH('08-apresentacao')});
  await p.keyboard.press('z'); await sleep(600);
  const zm=await p.evaluate(()=>{ const z=document.querySelector('#presenter .amp-zm'); return {open:!!z, fx:z?z.querySelectorAll('.fxpt').length:0, foot:z?z.textContent:''}; });
  await p.screenshot({path:SH('09-ampliar')});
  await p.keyboard.press('Escape'); await sleep(300); await p.keyboard.press('Escape'); await sleep(400);
  check('S07-20: na apresentação (F5 → slide 2) PDCA, Porter e BCG entram inteiros, são ampliáveis (o maior primeiro: Porter); Z abre o ampliado com o modelo re-renderizado e o rodapé “5 Forças de Porter”; Esc fecha o ampliado e depois sai da apresentação', pres.open&&/^02/.test(pres.pos)&&pres.fx==='111'&&pres.visible&&pres.zoomables==='porter,bcg,pdca'&&zm.open&&zm.fx===1&&/5 Forças de Porter/.test(zm.foot)&&await p.evaluate(()=>!document.getElementById('presenter').classList.contains('open')), {pres,zm});

  /* ---------- 10. saneamento ao abrir (safeEl + norm), export autônomo e reabertura ---------- */
  await fresh(p); for(const k of KINDS) await p.evaluate(k=>AMStudio.insertFx(k),k); await sleep(300);
  const d0=await p.evaluate(()=>JSON.parse(JSON.stringify(AMStudio.deck)));
  d0.slides[0].els.push({id:'tOld',type:'fx',kind:'issuetree',x:10,y:10,w:900,h:380,variant:'path',data:{items:'Raiz = 9 [*]\n  Filho [*]\n\tOutro',panel:'white'}}, {id:'tBad',type:'fx',kind:'gantt',x:10,y:10,w:900,h:380,variant:'nope',data:{periods:['A'],tasks:[{t:'x',s:0,e:1,k:'f'}],today:'A'}}, {id:'tNo',type:'fx',kind:'bcg',x:10,y:10,w:900,h:380,data:'texto'});
  await p.evaluate(d=>AMStudio.loadDeck(d,null,true,true), d0); await sleep(400);
  const ld=await p.evaluate(()=>{ const e=AMStudio.deck.slides[0].els, f=id=>e.filter(x=>x.id===id)[0]; return {n:e.length, old:{items:f('tOld').data.items, variant:f('tOld').variant, panel:f('tOld').data.panel}, bad:{variant:f('tBad').variant, tasks:f('tBad').data.tasks.length}, no:{items:f('tNo').data.items.length, q:f('tNo').data.q.length}, st:document.querySelectorAll('#wrap .am-stage .am-el .am-fxw > .fx').length}; });
  check('S07-21: ao abrir, safeEl + norm saneiam: itens da árvore em texto viram [{t, lv, v, hl}] (efeito e painel mantidos), efeito inválido cai, data inválido volta ao padrão do modelo; os 10 elementos renderizam', ld.n===10&&JSON.stringify(ld.old.items)==='[{"t":"Raiz","lv":0,"v":"9","hl":1},{"t":"Filho","lv":1,"hl":1},{"t":"Outro","lv":1}]'&&ld.old.variant==='path'&&ld.old.panel==='white'&&ld.bad.variant==null&&ld.bad.tasks===1&&ld.no.items===5&&ld.no.q===4&&ld.st===10, ld);
  const html=await p.evaluate(()=>AMStudio.exportHTML()); const f=path.join(TMP,'saved-s07.html'); fs.writeFileSync(f,html);
  const dj=deckJSON(html); const q=await page(ctx,'file://'+f,'exp',1500);
  const ex=await q.evaluate((KINDS)=>{ const sl=document.querySelectorAll('.amp .amp-slide'); return {slides:sl.length, rt:typeof AMRT!=='undefined'&&KINDS.every(k=>!!AMRT.FX[k])&&typeof AMRT.ganttPos==='function', ed:typeof AMStudio==='undefined'&&typeof AMCover==='undefined', fx:KINDS.map(k=>sl[0].querySelectorAll('.am-k-'+k+' .am-fxw > .fx').length).join(''), css:[...document.styleSheets].some(s=>{ try{ return [...s.cssRules].some(r=>/\.fxgt/.test(r.selectorText||'')); }catch(e){ return false; } }), kf:[...document.styleSheets].some(s=>{ try{ return [...s.cssRules].some(r=>r.name==='m7Spin'); }catch(e){ return false; } })}; },KINDS);
  await sleep(2500); await q.screenshot({path:SH('12-exportado')});
  check('S07-22: o arquivo exportado é autônomo (runtime + rt-models2, sem editor/capa), guarda o deck em #am-deck-data com os 10 modelos (árvore já como objetos), renderiza os 7 tipos no player com o CSS e os keyframes m7', ex.slides===1&&ex.rt&&ex.ed&&ex.fx==='1211122'&&ex.css&&ex.kf&&dj&&dj.slides[0].els.length===10&&dj.slides[0].els.filter(e=>e.kind==='issuetree').every(e=>Array.isArray(e.data.items)&&e.data.items.every(o=>typeof o.t==='string'))&&dj.slides[0].els.filter(e=>e.kind==='gantt').every(e=>Array.isArray(e.data.tasks)), {ex,n:dj&&dj.slides[0].els.length});
  check('S07-23: export sem onerror/onmouseover/onclick (CR-04) e sem “</script” fora das tags', !/onerror|onmouseover|onclick/i.test(html)&&(html.match(/<\/script/g)||[]).length===(html.match(/<script[\s>]/g)||[]).length, {s:(html.match(/<script[\s>]/g)||[]).length,e:(html.match(/<\/script/g)||[]).length});
  await q.close();
  const r=await page(ctx, FILE+'?nocover', 'reopen');
  await r.evaluate(h=>AMStudio.openFile(new File([h],'saved-s07.html',{type:'text/html'})), html); await sleep(1500);
  const ro=await r.evaluate((KINDS)=>{ const e=AMStudio.deck.slides[0].els; return {kinds:e.map(x=>x.kind).join(','), v:e.map(x=>x.variant||'-').join(','), gantt:e.filter(x=>x.kind==='gantt').map(x=>x.data.tasks.length+'/'+x.data.periods.length+'/'+x.data.today).join('|'), tree:e.filter(x=>x.kind==='issuetree').map(x=>x.data.items.length+'/'+x.data.items.filter(o=>o.hl).length).join('|'), bcg:e.filter(x=>x.kind==='bcg').map(x=>x.data.items.length).join('|'), st:KINDS.every(k=>document.querySelector('#wrap .am-stage .am-k-'+k+' .fx'))}; },KINDS);
  check('S07-24: reabrir o arquivo exportado no editor devolve os 10 modelos com dados e efeitos (Gantt 9 atividades / 6 períodos / hoje 2,4; árvore 9 itens com 3 no caminho e a antiga 3/2; BCG 5 unidades) e todos renderizam', ro.kinds==='pdca,gantt,asistobe,porter,roadmap,issuetree,bcg,issuetree,gantt,bcg'&&ro.v==='cycle,bars,reveal,converge,lanes,branch,drop,path,-,-'&&ro.gantt==='9/6/2.4|1/1/A'&&ro.tree==='9/3|3/2'&&ro.bcg==='5|5'&&ro.st, ro);
  await r.close();

  /* ---------- 11. painel de texto da árvore: Tab até o nível 3, edição em linha mantém valor e marcador ---------- */
  await fresh(p); await p.evaluate(()=>AMStudio.insertFx('issuetree')); await sleep(300);
  await p.fill('#props textarea[data-codec=outline]','Lucro = 100 [*]\n  Receita = 120 [*]\n    Preço = 80\n    Mix = 30\n  Custo = 20'); await sleep(300);
  const setCaret=(line)=>p.evaluate((line)=>{ const t=document.querySelector('#props textarea[data-codec=outline]'), ls=t.value.split('\n'); let pos=0; for(let i=0;i<line;i++) pos+=ls[i].length+1; t.focus(); t.setSelectionRange(pos+2,pos+2); },line);
  await setCaret(3); await p.keyboard.press('Tab'); await sleep(200); const k1=await p.evaluate(()=>({v:document.querySelector('#props textarea[data-codec=outline]').value.split('\n')[3], lv:AMStudio.deck.slides[0].els[0].data.items[3].lv, active:document.activeElement.tagName}));
  await p.keyboard.press('Tab'); await sleep(200); const k2=await p.evaluate(()=>({v:document.querySelector('#props textarea[data-codec=outline]').value.split('\n')[3], lv:AMStudio.deck.slides[0].els[0].data.items[3].lv, d3:document.querySelectorAll('#wrap .am-stage .it-n.d3').length, items:AMStudio.deck.slides[0].els[0].data.items.map(o=>o.lv+':'+o.t+(o.v?'='+o.v:'')+(o.hl?'*':'')).join(',')}));
  await p.keyboard.press('Escape'); await sleep(200);
  const vsp=await p.$('#wrap .am-stage [data-e="items.1.t"]'); const vb=await vsp.boundingBox(); await p.mouse.dblclick(vb.x+vb.width/2, vb.y+vb.height/2); await sleep(200);
  const ce2=await p.evaluate(()=>{ const a=document.activeElement; return {ce:a&&a.isContentEditable, path:a&&a.dataset.e, txt:a&&a.textContent}; });
  await p.keyboard.type('Receita líquida'); await p.keyboard.press('Enter'); await sleep(300);
  const ie2=await p.evaluate(()=>{ const it=AMStudio.deck.slides[0].els[0].data.items[1]; return {t:it.t, v:it.v, hl:it.hl, ta:document.querySelector('#props textarea[data-codec=outline]').value.split('\n')[1], val:document.querySelector('#wrap .am-stage [data-e="items.1.v"]').textContent}; });
  const vsp2=await p.$('#wrap .am-stage [data-e="items.1.v"]'); const vb2=await vsp2.boundingBox(); await p.mouse.dblclick(vb2.x+vb2.width/2, vb2.y+vb2.height/2); await sleep(200); await p.keyboard.type('135'); await p.keyboard.press('Enter'); await sleep(300);
  const ie3=await p.evaluate(()=>{ const it=AMStudio.deck.slides[0].els[0].data.items[1]; return {t:it.t, v:it.v, ta:document.querySelector('#props textarea[data-codec=outline]').value.split('\n')[1]}; });
  await p.screenshot({path:SH('13-arvore-kpi')});
  check('S07-25: painel de texto da árvore: Tab leva “Mix” ao nível 3 (6 espaços, nó d3 no palco) e para nele (data-maxlv=3), sem tirar o foco; duplo clique no título “Receita” edita só o título (items.1.t), Enter grava “Receita líquida” mantendo o valor 120 e o “[*]” (painel “  Receita líquida = 120 [*]”); duplo clique no valor edita items.1.v → 135', k1.v==='      Mix = 30'&&k1.lv===3&&k1.active==='TEXTAREA'&&k2.v==='      Mix = 30'&&k2.lv===3&&k2.d3===1&&k2.items==='0:Lucro=100*,1:Receita=120*,2:Preço=80,3:Mix=30,1:Custo=20'&&ce2.ce&&ce2.path==='items.1.t'&&ce2.txt==='Receita'&&ie2.t==='Receita líquida'&&ie2.v==='120'&&ie2.hl===1&&ie2.ta==='  Receita líquida = 120 [*]'&&ie2.val==='120'&&ie3.v==='135'&&ie3.t==='Receita líquida'&&ie3.ta==='  Receita líquida = 135 [*]', {k1,k2,ce2,ie2,ie3});

  /* ---------- 13. QA 1 (fixer): Porter e PDCA ajustam a fonte ao texto, gancho norm dos 6 modelos, rótulos da BCG desviam, dicas ---------- */
  /* varredura interna de um modelo no palco do editor: textos editáveis (+ títulos das listas) que se sobrepõem, cards/listas cortados (scroll > client) e inline style com NaN/negativo */
  const scan=p=>p.evaluate(()=>{ const st=document.querySelector('#wrap .am-stage'), out={overlap:[],clipped:[],bad:[]}, R=[];
    st.querySelectorAll('[data-e],.pd-l b').forEach(s=>{ if(!s.textContent.trim()) return; const rs=[...s.getClientRects()].filter(r=>r.width>0&&r.height>0); if(!rs.length) return; R.push({s,t:s.textContent.trim().slice(0,24),u:rs.reduce((a,r)=>({l:Math.min(a.l,r.left),t:Math.min(a.t,r.top),r:Math.max(a.r,r.right),b:Math.max(a.b,r.bottom)}),{l:1e9,t:1e9,r:-1e9,b:-1e9})}); });
    for(let i=0;i<R.length;i++) for(let j=i+1;j<R.length;j++){ const a=R[i],b=R[j]; if(a.s.contains(b.s)||b.s.contains(a.s)) continue; const w=Math.min(a.u.r,b.u.r)-Math.max(a.u.l,b.u.l), h=Math.min(a.u.b,b.u.b)-Math.max(a.u.t,b.u.t); if(w>2&&h>2) out.overlap.push(a.t+' × '+b.t); }
    st.querySelectorAll('.pt-f,.pt-c,.pd-l,.pd-c').forEach(e=>{ if(e.scrollHeight>e.clientHeight+1||e.scrollWidth>e.clientWidth+1) out.clipped.push(e.className+':'+e.textContent.trim().slice(0,24)); });
    st.querySelectorAll('.pt-f b,.pt-f>span:not(.pt-dots),.pd-l li,.pd-l b').forEach(e=>{ if(e.scrollWidth>e.clientWidth+1) out.clipped.push('largura '+e.className+':'+e.textContent.trim().slice(0,24)); }); /* corte horizontal (texto sem espaços) */
    st.querySelectorAll('.fx [style]').forEach(e=>{ if(/NaN|Infinity|undefined|(?:width|height|left|top|right|bottom|font-size)\s*:\s*-\d/.test(e.getAttribute('style'))) out.bad.push(e.getAttribute('style').slice(0,80)); }); /* variáveis de animação (--rx/--ry da rampa) são negativas por desenho */
    const fx=st.querySelector('.fx'), card=st.querySelector('.pt-f,.pd-l'); out.k=card?Math.round(parseFloat(getComputedStyle(card).fontSize)/parseFloat(getComputedStyle(fx).fontSize)*100)/100:null;
    out.cmt=st.querySelectorAll('.pt-f>span:not(.pt-dots)').length; out.ell=[...st.querySelectorAll('.pt-f b,.pt-f>span:not(.pt-dots)')].filter(s=>s.scrollHeight>s.clientHeight+1).length; out.lb=[...st.querySelectorAll('.bc-lb')].map(l=>l.className.replace('bc-lb','').trim()||'r').join('');
    return out; });
  const put=async(k,data,v)=>{ await fresh(p); await p.evaluate(([k,d,v])=>{ const el=AMStudio.insertFx(k); Object.keys(d).forEach(q=>{ el.data[q]=d[q]; }); if(v) el.variant=v; AMStudio.renderAll(); AMStudio.commit(); },[k,data,v||null]); await sleep(350); return scan(p); };
  const pf=(t,n,x)=>({t,n,x});
  const q1=await put('porter',{forces:[pf('Novos entrantes',2,'Capital intensivo e regulação setorial limitam a entrada no curto prazo'),pf('Poder dos fornecedores',4,'3 fornecedores detêm 80% do insumo crítico e repassam custos com facilidade ao setor'),pf('Poder dos clientes',3,'Grandes redes negociam preço e prazo com forte alavancagem comercial'),pf('Substitutos',5,'Soluções digitais avançam rápido')]});
  await p.screenshot({path:SH('14-porter-comentarios')});
  const q2=await put('porter',{center:'Rivalidade entre os concorrentes estabelecidos no mercado nacional',cn:5,forces:[pf('Ameaça de novos entrantes no segmento',2,'Capital intensivo, regulação setorial e escala limitam a entrada de novos competidores no curto prazo'),pf('Poder de barganha dos fornecedores de insumos',4,'3 fornecedores detêm 80% do insumo crítico e repassam custos com facilidade'),pf('Poder de barganha dos clientes e grandes redes',3,'Grandes redes negociam preço e prazo com forte alavancagem'),pf('Ameaça de produtos e serviços substitutos',5,'Soluções digitais avançam rápido e capturam parte do valor')]});
  const c2=await p.evaluate(()=>{ const b=document.querySelector('#wrap .am-stage .pt-c b'); return {t:b.textContent, ell:b.scrollHeight>b.clientHeight+1}; }); /* centro de 66 letras inteiro (cap 80), sem reticências */
  const q3=await put('porter',{});
  const WW='WWWWWWWWW '.repeat(12).trim(); /* 119 letras largas: a estimativa (,53 em por letra) fica curta e o line-clamp tem de segurar com reticências */
  const q4=await put('porter',{forces:[pf('Novos entrantes',2,WW),pf('Poder dos fornecedores de insumos críticos e de capital intensivo',4,WW),pf('Clientes',3,WW),pf('Substitutos',5,WW)]}); await p.screenshot({path:SH('14b-porter-clamp')});
  const q5=await put('porter',{forces:[pf('Novos entrantes',2,'x'.repeat(120)),pf('Poder dos fornecedores de insumos críticos e de capital intensivo',4,'y'.repeat(120)),pf('Clientes',3,''),pf('Substitutos',5,'z'.repeat(120))]});
  check('S07-27: Porter ajusta a fonte ao texto: comentários de 32–86 caracteres (D1 da QA) cabem sem corte do card, com os 4 comentários visíveis e fonte reduzida (fator entre 0,62 e 1); dados de estresse (nomes de 37–46, comentários de 58–100) idem; o centro de 66 letras aparece inteiro (“…mercado nacional”, sem reticências); o padrão mantém o fator 1; comentários de 119 letras largas (W) e nome de 65 letras: a estimativa fica curta, o line-clamp termina em reticências e o card não corta; 120 letras sem espaço quebram (overflow-wrap) sem corte horizontal; o inline style nunca tem NaN/negativo', !q1.clipped.length&&q1.cmt===4&&q1.ell===0&&q1.k<1&&q1.k>=.62&&!q2.clipped.length&&q2.cmt===4&&q2.ell===0&&/mercado nacional$/.test(c2.t)&&!c2.ell&&q3.k===1&&q3.cmt===4&&!q4.clipped.length&&q4.ell>0&&q4.k>=.62&&q4.k<1&&!q5.clipped.length&&q5.k>=.62&&!q1.bad.length&&!q4.bad.length&&!q5.bad.length, {q1,q2,c2,q3,q4,q5});
  const acts=['Definir metas e indicadores por frente','Mapear causas-raiz com as equipes','Priorizar hipóteses de maior impacto','Montar o plano de ação detalhado','Alinhar com o comitê executivo'];
  const d1=await put('pdca',{p:acts,d:acts,c:acts,a:acts}); await p.screenshot({path:SH('15-pdca-5acoes')});
  const d2=await put('pdca',{p:acts.map(a=>a.slice(0,27)),d:acts.map(a=>a.slice(0,27)),c:acts.map(a=>a.slice(0,27)),a:acts.map(a=>a.slice(0,27))});
  const six=acts.concat(['Comunicar às áreas envolvidas e consolidar os ganhos']);
  const d3=await put('pdca',{names:['Planejar com cuidado e método','Executar em ondas','Verificar com indicadores','Agir e padronizar'],p:six,d:six,c:six,a:six});
  const d4=await put('pdca',{p:acts,d:acts,c:acts,a:acts},'ramp');
  const d5=await p.evaluate(()=>[...document.querySelectorAll('#wrap .am-stage .pd-l')].map(l=>{ const cs=getComputedStyle(l); return cs.maxHeight+'/'+cs.overflow; }).join(','));
  check('S07-28: PDCA: 5 ações de ~38 caracteres por fase (D2 da QA) não se sobrepõem entre listas nem aos nomes das fases, nenhuma lista cortada, fonte reduzida (0,6–1); 5 ações curtas (≤ 27) mantêm o fator 1; 6 ações longas com nomes de fase longos também sem sobreposição nem corte; na rampa idem; cada lista vive numa faixa de 46 % com overflow oculto', !d1.overlap.length&&!d1.clipped.length&&d1.k<1&&d1.k>=.6&&!d2.overlap.length&&d2.k===1&&!d3.overlap.length&&!d3.clipped.length&&!d4.overlap.length&&d5==='46%/hidden,46%/hidden,46%/hidden,46%/hidden', {d1,d2,d3,d4,d5});
  /* gancho norm dos 6 modelos: lista em texto vira array, linhas em texto viram objetos; a edição no slide grava num array (sem erro de página) */
  const nd=await p.evaluate(()=>JSON.parse(JSON.stringify(AMStudio.newDeck())));
  const mkEl=(id,kind,data,x,y)=>({id,type:'fx',kind,x,y,w:600,h:220,data}); /* 2 colunas × 3 linhas, sem sobreposição */
  nd.slides[0].els.push(mkEl('nPd','pdca',{p:'Alfa;Beta',names:'X;Y;Z;W',letters:['P','D','C','A']},20,20),mkEl('nGt','gantt',{periods:'Jan;Fev;Mar',tasks:'Kickoff | Jan | Jan | m\nOnda 1 | 0 | 2,5 | c',today:'Fev'},660,20),mkEl('nAb','asistobe',{rows:'Governança | Hoje | Amanhã\nDados | Planilhas | Base única'},20,250),mkEl('nPt','porter',{forces:'Entrantes | 2 | ok\nFornecedores | 5 | forte',center:'Rivalidade',cn:3},660,250),mkEl('nRm','roadmap',{cols:'H1;H2',lanes:'A\nB',items:'Piloto | 1 | 0 | 1 | c\nMarco | 2 | 1,5 | 1,5 | m'},20,480),mkEl('nBc','bcg',{q:'E;P;V;A',items:['Premium | 70 | 60 | 30',{t:'Básica',x:20,y:20,s:10},null]},660,480));
  const errsN=errs.length; await p.evaluate(d=>AMStudio.loadDeck(d,null,true,true),nd); await sleep(500);
  const nm=await p.evaluate(()=>{ const e=AMStudio.deck.slides[0].els, f=id=>e.filter(x=>x.id===id)[0].data, st=document.querySelector('#wrap .am-stage'); return {pd:JSON.stringify([f('nPd').p,f('nPd').names]), gt:JSON.stringify(f('nGt').tasks)+'|'+JSON.stringify(f('nGt').periods), ab:f('nAb').rows.length+':'+f('nAb').rows[1].b, pt:f('nPt').forces.map(x=>x.t+'/'+x.n).join(','), rm:JSON.stringify(f('nRm').items[1])+'|'+f('nRm').cols.join('+')+'|'+f('nRm').lanes.join('+'), bc:JSON.stringify(f('nBc').items)+'|'+f('nBc').q.join(''), st:{gt:st.querySelectorAll('.am-k-gantt .gt-r').length, ms:st.querySelectorAll('.am-k-gantt .gt-ms').length, ab:st.querySelectorAll('.ab-t').length, pt:st.querySelectorAll('.pt-f').length, rm:st.querySelectorAll('.rm-ch,.rm-ms').length, bc:st.querySelectorAll('.bc-b').length, pd:[...st.querySelectorAll('.am-k-pdca .pd-l b')].map(b=>b.textContent).join('')}}; });
  const sp=await p.$('#wrap .am-stage .am-k-pdca [data-e="p.0"]'); const sb=await sp.boundingBox(); await p.mouse.dblclick(sb.x+sb.width/2,sb.y+sb.height/2); await sleep(200); await p.keyboard.type('Gama'); await p.keyboard.press('Enter'); await sleep(350);
  const ne=await p.evaluate(()=>({p:JSON.stringify(AMStudio.deck.slides[0].els.filter(x=>x.id==='nPd')[0].data.p), editing:!!document.querySelector('#wrap .am-stage [contenteditable]'), shown:document.querySelector('#wrap .am-stage .am-k-pdca [data-e="p.0"]').textContent}));
  const errs2=errs.splice(errsN); /* erros desta etapa contam só aqui */
  check('S07-29: ao abrir um arquivo editado à mão, o gancho norm dos 6 modelos converte listas em texto (“Alfa;Beta”, “X;Y;Z;W”, “A\\nB”) em arrays e linhas em texto (“nome | início | fim | tipo”) em objetos (strings ficam strings: “2,5”, “Jan”), mantendo objetos já válidos e descartando nulos (a linha nula da BCG fica como {} no índice 2 e não vira bolha); tudo renderiza (Gantt 2 linhas com 1 marco, 2 dimensões, 2 forças, 2 iniciativas, 2 bolhas, nomes X Y Z W) e o duplo clique na 1ª ação do PDCA grava “Gama” no array sem erro de página nem edição presa', nm.pd==='[["Alfa","Beta"],["X","Y","Z","W"]]'&&nm.gt==='[{"t":"Kickoff","s":"Jan","e":"Jan","k":"m"},{"t":"Onda 1","s":"0","e":"2,5","k":"c"}]|["Jan","Fev","Mar"]'&&nm.ab==='2:Base única'&&nm.pt==='Entrantes/2,Fornecedores/5'&&nm.rm==='{"t":"Marco","l":"2","s":"1,5","e":"1,5","k":"m"}|H1+H2|A+B'&&nm.bc==='[{"t":"Premium","x":"70","y":"60","s":"30","tx":"","ty":""},{"t":"Básica","x":20,"y":20,"s":10},{}]|EPVA'&&nm.st.gt===2&&nm.st.ms===1&&nm.st.ab===2&&nm.st.pt===2&&nm.st.rm===2&&nm.st.bc===2&&nm.st.pd==='XYZW'&&ne.p==='["Gama","Beta"]'&&!ne.editing&&ne.shown==='Gama'&&errs2.length===0, {nm,ne,errs2});
  /* rótulos da BCG desviam de bolhas vizinhas, de rótulos já postos e dos nomes dos quadrantes */
  const b1=await put('bcg',{items:[{t:'Unidade Norte',x:60,y:60,s:30},{t:'Unidade Sul',x:66,y:56,s:20},{t:'Atacado',x:80,y:26,s:48},{t:'Linha básica',x:30,y:22,s:12}]}); await p.screenshot({path:SH('16-bcg-vizinhas')});
  const b2=await put('bcg',{items:[{t:'Unidade Alfa',x:50,y:50,s:30},{t:'Unidade Beta',x:62,y:50,s:30},{t:'Unidade Gama',x:38,y:50,s:30}]});
  const b3=await put('bcg',{items:[['Linha premium de produtos',78,72,34],['Varejo digital',28,80,16,62,76],['Atacado e distribuição',80,26,48],['Linha básica',30,22,12],['Serviços',42,56,20,64,64],['Nova unidade A',75,70,30],['Nova unidade B',72,68,10,80,80],['Unidade C',50,50,25],['Unidade D',52,48,25],['Unidade E',10,10,5],['Unidade F',95,95,60],['Unidade G',20,90,8,70,90]].map(i=>({t:i[0],x:i[1],y:i[2],s:i[3],tx:i[4],ty:i[5]}))}); await p.screenshot({path:SH('17-bcg-agrupada')});
  const b4=await p.evaluate(()=>{ const st=document.querySelector('#wrap .am-stage'), q=st.querySelector('.bc-q0').getBoundingClientRect(), f=[...st.querySelectorAll('.bc-lb')].filter(l=>/Unidade F/.test(l.textContent))[0].getBoundingClientRect(), qr=document.createRange(); qr.selectNodeContents(st.querySelector('.bc-q0 [data-e]')); const t=qr.getBoundingClientRect(); return {w:Math.min(f.right,t.right)-Math.max(f.left,t.left), h:Math.min(f.bottom,t.bottom)-Math.max(f.top,t.top)}; });
  const b5=await put('bcg',{});
  check('S07-30: rótulos da BCG: duas bolhas a 6 pontos (E5 da QA) não sobrepõem os textos (o 2º rótulo vai para a esquerda: r l r l); bolha com vizinhas dos dois lados manda o rótulo para cima (u l r, classes .u/.d com transform centrado); 12 unidades agrupadas sem nenhuma sobreposição de texto e “Unidade F” (canto) não cobre o nome do quadrante; o padrão mantém os lados R R R L R', !b1.overlap.length&&b1.lb==='rlrl'&&!b2.overlap.length&&b2.lb==='ulr'&&!b3.overlap.length&&!b3.bad.length&&!(b4.w>2&&b4.h>2)&&b5.lb==='rrrlr', {b1:{overlap:b1.overlap,lb:b1.lb},b2:{overlap:b2.overlap,lb:b2.lb},b3:{overlap:b3.overlap,lb:b3.lb},b4,b5:b5.lb});
  const tips=await p.evaluate(()=>({it:AMRT.FX.issuetree.tip, gt:AMRT.FX.gantt.tip, pt:AMRT.FX.porter.tip, pd:AMRT.FX.pdca.tip, bc:AMRT.FX.bcg.tip, norm:['pdca','gantt','asistobe','porter','roadmap','bcg'].every(k=>typeof AMRT.FX[k].norm==='function')}));
  check('S07-31: as dicas dizem o limite prático: árvore “até 20 nós … Ampliar (Z)”, Gantt “até 14 atividades … Ampliar (Z)”, Porter “≈60 caracteres … reticências”, PDCA “5 ações curtas (≈30 caracteres)”, BCG “rótulos desviam”; os 6 modelos têm o gancho norm', /20 nós/.test(tips.it)&&/Ampliar \(Z\)/.test(tips.it)&&/14 atividades/.test(tips.gt)&&/Ampliar \(Z\)/.test(tips.gt)&&/60 caracteres/.test(tips.pt)&&/reticências/.test(tips.pt)&&/5 ações curtas \(≈30 caracteres\)/.test(tips.pd)&&/desviam/.test(tips.bc)&&tips.norm, tips);

  /* ---------- 12. barra de ferramentas sem estouro (nenhum botão novo) ---------- */
  await p.setViewportSize({width:1280,height:720}); await sleep(400);
  const ov=await p.evaluate(()=>{const t=document.getElementById('top'), rb=document.getElementById('rib'), s=document.getElementById('bSave').getBoundingClientRect(); return {top:t.scrollWidth<=t.clientWidth, rib:rb.scrollWidth<=rb.clientWidth, save:s.right<=innerWidth}; });
  check('S07-26: barra de ferramentas e topo sem estouro em 1280 (os modelos vivem na Biblioteca de modelos; nenhum botão novo)', ov.top&&ov.rib&&ov.save, ov);

  check('Zero erros de console', errs.length===0, errs);
  console.log(results.join('\n'));
  console.log(failed?('FALHAS: '+failed):'TUDO OK', JSON.stringify({errs}));
  await b.close(); try{ fs.rmSync(TMP,{recursive:true,force:true}); }catch(e){}
  process.exit(failed?1:0);
})().catch(e=>{ console.log(results.join('\n')); console.error('ERRO', e); process.exit(2); });
